### ISSUE TITLE
Valheim character and world data lost when BepInEx console closed before closing game

### ISSUE THREAD

**Issue by Gr3atsaga** [BepInEx/BepInEx#215] opened 2021-03-16 22:21 UTC
**Describe the bug**

After installing BepInEx for Valheim in order to use mods from NexusMods, I am experiencing an issue with world and character data being lost when closing the console before the game is closed or at the main menu.

If the BepInEx console is closed while you are connected to a world in Valheim, this will close the game and the console.  However when loading the game again and entering a world with the same character, anything that had been done prior was not saved.  I.E. character progression and inventory, as well as world data itself if playing with a world locally.  This also allows for item duplication if playing on a dedicated server as anything removed from the player inventory will be put into the world, but retained on the character also after experiencing the bug.

**To Reproduce**

1) Run Valhiem with BepInEx installed
2) Start Game -> Select a Character -> Select World -> Start
3) Pick up/remove items from character inventory
4) Build/remove something from the world
5) Without logging out, or exiting to the main menu, or otherwise closing the game itself, navigate to the BepInEx console and close it.  
6) Run the game again, select the same character and same world and observe that character and world data was lost.

**Expected behavior**

Character data and world data saved when the BepInEx console is closed prior to the game being closed.

**Screenshots and logs**

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 
 - BepInEx version [e.g. 4.0]: 
 
 Game: Valheim Version 0.147.3
 BepInEx Version 5.4.8.0

**Additional context**

This issue occurs without any mods/plugins installed.  Just the BepInEx package.

**Comment by Razzmatazzz** [comment] 2021-03-17 00:05
A little background info for the BepInEx devs: Valheim saves every 20 minutes. A save is also triggered when the player quits the game. It sounds like when BepInEx is closed, it kills Valheim without "gracefully" shutting down and triggering a save. 

If there's a way to feed the "save" console command to Valheim prior to being shutdown, that would cause the game to save. But if BepInEx is just terminating the Valheim process, triggering the save command and then terminating it could be the worst of all worlds as it might cause the game to start saving but then get terminated halfway through which would leave the user with a corrupted save file.

**Comment by Gr3atsaga** [comment] 2021-03-17 14:42
Also to clarify, Valheim itself will still close gracefully if forced closed from task manager.  I tested both on singleplayer and on a dedicated server and both times I force closed the exe in task manager and the game still saved my data.  Indeed Valhiem is closing gracefully even when forcing termination.

**Comment by ghorsington** [comment] 2021-03-17 15:22
Greetings!

Thank you for the extensive report and a clear description of how to reproduce the issue. As you mentioned, this problem is game-specific and is related to how console works in Windows in general.

Unfortunately there is nothing much reasonable that can be done on BepInEx side. As outlined [in a very relevant StackOverflow answer](https://stackoverflow.com/questions/11959643/why-does-closing-a-console-that-was-started-with-allocconsole-cause-my-whole-app), there is no way to programmatically add a handler to the exit button. The best that can be done is being able to hide the close button in console altogether. However it does not appear to prevent you from closing the console via window preview, the taskbar or the Alt+Tab application switcher. 

As such just like you speculated, this is a fairly strong "wontfix" on BepInEx side. We are investigating the possibility of bundling a custom terminal emulator with BepInEx, but it is only being planned. Meanwhile I suggest either disabling the console via BepInEx configuation or simply not closing the game with it.

At the end of the day, there is only so much that can be done to prevent user from closing their game gracefully 😅. From game design perspective, 20 minute period for autosaving is not great in my opinion. I would urge Valheim developers or modders adjust it to, say, 5 minute intervals.

**Comment by Gr3atsaga** [comment] 2021-03-17 22:57
Thank you for the response.  I did not realize you could disable to console.  That is a satisfactory work around when actually playing the game.  If ever needed I can re-enable it for debugging.  My main concern was that I am playing with someone that may not remember not to close the console (younger, less tech savvy).  I can disable their console permanently and it should be okay.

**Comment by ghorsington** [comment] 2021-03-21 18:09
Support for prevent console from being closed (by disabling the close button) was added in 1b6537b2a1b67b26bfc7f171ee64fa1b40dc4113 and will be part of 5.4.9. As such, I'm going to close this issue since there is not much else that can be done on our side to this.

**Closed by ghorsington** 2021-03-21 18:09 UTC
Labels: game-specific, windows
