### ISSUE TITLE
BepInEx breaks the AchievementManager in the new Risk of Rain 2 update

### ISSUE THREAD

**Issue by Chirimorin** [BepInEx/BepInEx#404] opened 2022-04-21 12:27 UTC
### What happened?

The latest Risk of Rain 2 update changed some things in the background and now the AchievementManager fails to load correctly. This breaks the logbook and probably obtaining achievements. The game works as intended when playing unmodded, but not when playing modded with only BepInExPack installed. 

### Steps to reproduce

1. Install BepInEx through R2Modman on a new profile
2. Start modded game in R2Modman
3. RoR2.AchievementManager throws an TargetInvocationException during loading (see log output)
4. Click the logbook
5. RoR2.AchievementManager throws a NullReferenceException on an enumerator (see log output), the logbook does not load properly

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
[Message:   BepInEx] BepInEx 5.4.19.0 - Risk of Rain 2 (3/1/2022 5:02:18 PM)
[Info   :   BepInEx] Running under Unity v2019.4.26.14694700
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Message:BepInEx.GUI.Patcher] Finding and launching GUI
[Info   :   BepInEx] Patching [RoR2] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [RoR2BepInExPack 1.0.1]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
[Info   : Unity Log] buildId = 1.2.3.1
[Info   : Unity Log] WwiseUnity: Wwise(R) SDK Version 2019.2.12 Build 7544.
[Info   : Unity Log] WwiseUnity: Setting Plugin DLL path to: G:/SteamLibrary/steamapps/common/Risk of Rain 2/Risk of Rain 2_Data\Plugins\x86_64
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Info   : Unity Log] Loaded scene loadingbasic loadSceneMode=2
[Info   : Unity Log] application data path isG:/SteamLibrary/steamapps/common/Risk of Rain 2/Risk of Rain 2_Data
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   : Unity Log] PlatformSystems:InitNetworkManagerSystem
[Info   : Unity Log] Launch Parameters: 
  arg[0]="G:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"
  arg[1]="--doorstop-enable"
  arg[2]="true"
  arg[3]="--doorstop-target"
  arg[4]="C:\Users\chiri\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\core\BepInEx.Preloader.dll"

[Info   : Unity Log] "usesocialiconflag" is not a recognized ConCommand or ConVar.
[Info   : Unity Log] Loaded archived convars.
[Info   : Unity Log] Could not load config /Config/autoexec.cfg: Could not find file "G:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\autoexec.cfg"
[Info   : Unity Log] LoadContentPacks() start
[Warning: Unity Log] Failed to assign Buffs.Deafened: Asset "bdDeafened" not found.
[Warning: Unity Log] Failed to assign Items.SummonedEcho: Asset "SummonedEcho" not found.
[Warning: Unity Log] Failed to assign Equipment.AffixEcho: Asset "EliteEchoEquipment" not found.
[Warning: Unity Log] Failed to assign Buffs.AffixEcho: Asset "bdEliteEcho" not found.
[Warning: Unity Log] Failed to assign Elites.Echo: Asset "edEcho" not found.
[Info   : Unity Log] LoadContentPacks() end
[Warning: Unity Log] Could not find scene with name "loadingbasic".
[Warning: Unity Log] Could not find scene with name "intro".
[Info   : Unity Log] Command "set_scene" failed: "intro" is not a valid scene.
[Info   : Unity Log] Game content load completed in 11559ms.
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] [RoR2.Stats.StatSheet] init stat sheet
[Error  : Unity Log] [RoR2.AchievementManager] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <44afb4564e9347cf99a1865351ea8f4a>:0 
  at RoR2.AchievementManager.CollectAchievementDefs (System.Collections.Generic.Dictionary`2[TKey,TValue] map) [0x00081] in <7a5120bd69d843a8b8e90b8cce404663>:0 
  at RoR2.AchievementManager.DoInit () [0x00000] in <7a5120bd69d843a8b8e90b8cce404663>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <44afb4564e9347cf99a1865351ea8f4a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0004b] in <44afb4564e9347cf99a1865351ea8f4a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <44afb4564e9347cf99a1865351ea8f4a>:0 
  at RoR2.SystemInitializerAttribute.Execute () [0x00174] in <7a5120bd69d843a8b8e90b8cce404663>:0 
[Info   : Unity Log] SystemInitializerAttribute infinite loop detected. currentMethod=RoR2.UI.LogBook.LogBookControllerInit
[Info   : Unity Log] initializer dependencies = RoR2.BodyCatalog,
RoR2.SceneCatalog,
RoR2.AchievementManager,
RoR2.ItemCatalog,
RoR2.EquipmentCatalog,
RoR2.UnlockableCatalog,
RoR2.RunReport,
RoR2.SurvivorCatalog,
RoR2.EntitlementManagement.EntitlementManager,
RoR2.ExpansionManagement.ExpansionCatalog
[Info   : Unity Log] initialized types = RoR2.ArtifactCatalog,
RoR2.BackstabManager,
RoR2.BackstabManager+BackstabVisualizer,
RoR2.BadClientEntityStateMachineFix,
RoR2.BodyCatalog,
RoR2.BuffCatalog,
RoR2.BulletAttack,
RoR2.CostTypeCatalog,
RoR2.GameEndingCatalog,
RoR2.EffectCatalog,
RoR2.EliteCatalog,
RoR2.EntityStateCatalog,
RoR2.EquipmentCatalog,
RoR2.FileIoIndicatorManager,
RoR2.CombatDirector,
RoR2.DebugOverlay,
RoR2.DotController,
RoR2.GenericPickupController,
RoR2.NetworkUIPromptController,
RoR2.PickupDropletController,
RoR2.RayAttackIndicator,
RoR2.RunArtifactManager,
RoR2.TeamComponent,
RoR2.ItemTierCatalog,
RoR2.MasterCatalog,
RoR2.MiscPickupCatalog,
RoR2.MorgueManager,
RoR2.MusicTrackCatalog,
RoR2.ProjectileCatalog,
RoR2.SceneCatalog,
RoR2.SkinCatalog,
RoR2.SurfaceDefCatalog,
RoR2.SurvivorCatalog,
RoR2.GamepadVibration.GamepadVibrationController,
RoR2.GamepadVibration.GamepadVibrationManager,
RoR2.Skills.SkillCatalog,
RoR2.CharacterSpeech.BrotherSpeechDriver,
RoR2.ExpansionManagement.ExpansionCatalog,
RoR2.EntitlementManagement.EntitlementCatalog,
RoR2.EntitlementManagement.EntitlementManager,
RoR2.UI.EnemyInfoPanel,
RoR2.UI.UILayerKey,
RoR2.UI.MainMenu.MainMenuController,
RoR2.Audio.NetworkSoundEventCatalog,
RoR2.Artifacts.BombArtifactManager,
RoR2.Artifacts.CommandArtifactManager,
RoR2.Artifacts.DoppelgangerInvasionManager,
RoR2.Artifacts.EnigmaArtifactManager,
RoR2.Artifacts.FriendlyFireArtifactManager,
RoR2.Artifacts.SacrificeArtifactManager,
RoR2.Artifacts.SwarmsArtifactManager,
RoR2.Artifacts.TeamDeathArtifactManager,
RoR2.ArtifactMask,
RoR2.ItemCatalog,
RoR2.Loadout,
RoR2.Loadout+BodyLoadoutManager,
RoR2.PickupCatalog,
RoR2.PickupTransmutationManager,
RoR2.ProjectileGhostReplacementManager,
RoR2.RuleCatalog,
RoR2.SerializableLoadout,
RoR2.UnlockableCatalog,
RoR2.Stats.StatDef,
RoR2.Stats.StatManager,
RoR2.Stats.StatSheet,
RoR2.Items.BaseItemBodyBehavior,
RoR2.Items.ContagiousItemManager,
RoR2.Items.CrippleWardOnLevelManager,
RoR2.Items.ExtraLifeVoidManager,
RoR2.Items.SuppressedItemManager,
RoR2.Items.UseAmbientLevelManager,
RoR2.Items.WardOnLevelManager,
RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager,
RoR2.NetworkExtensions,
RoR2.CostTypeCatalog+LunarItemOrEquipmentCostTypeHelper,
RoR2.CharacterSpawnCard,
RoR2.ItemDisplayRuleSet,
RoR2.PreGameRuleVoteController,
RoR2.ShrineCleanseBehavior,
RoR2.GameModeCatalog,
RoR2.GoldTitanManager,
RoR2.RuleBook,
RoR2.SteamworksLobbyDataGenerator,
RoR2.EOSLobbyDataGenerator
[Info   : Unity Log] Attempting to load user profile /UserProfiles/2f7e0cb6-aa16-4792-835e-302ed80accfb.xml
[Info   : Unity Log] stream.Length=249083
[Info   : Unity Log] Unloaded scene loadingbasic
[Info   : Unity Log] Active scene changed from  to splash
[Info   : Unity Log] Loaded scene splash loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to intro
[Info   : Unity Log] Unloaded scene splash
[Info   : Unity Log] Active scene changed from  to intro
[Info   : Unity Log] Loaded scene intro loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene intro
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] BaseMainMenuScreen: OnEnter()
[Info   : Unity Log] Setting offline scene to logbook
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to logbook
[Info   : Unity Log] Loaded scene logbook loadSceneMode=Single
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.AchievementManager+Enumerator.MoveNext () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].MoveNext () (at <55b3683038794c198a24e8a1362bfc61>:0)
System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) (at <55b3683038794c198a24e8a1362bfc61>:0)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <55b3683038794c198a24e8a1362bfc61>:0)
RoR2.UI.LogBook.LogBookController.BuildAchievementEntries (System.Collections.Generic.Dictionary`2[TKey,TValue] expansionAvailability) (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.UI.LogBook.LogBookController.BuildCategories () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.UI.LogBook.LogBookController.BuildStaticData () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.UI.LogBook.LogBookController.Init () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.UI.LogBook.LogBookController.GeneratePages (RoR2.UserProfile viewerProfile) (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.UI.LogBook.LogBookController.Start () (at <7a5120bd69d843a8b8e90b8cce404663>:0)

[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene logbook
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] BaseMainMenuScreen: OnEnter()
[Info   : Unity Log] Saved file "2f7e0cb6-aa16-4792-835e-302ed80accfb.xml" (249083 bytes)
[Info   : Unity Log] in save archive convars
[Info   : Unity Log] Shutting down Steamworks...
[Info   : Unity Log] Shut down Steamworks.
[Error  :BepInEx.GUI.Patcher] System.Threading.ThreadAbortException
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_thread_interruption_checkpoint()
  at (wrapper managed-to-native) System.Threading.Thread.YieldInternal()
  at System.Threading.Thread.Yield () [0x00000] in <44afb4564e9347cf99a1865351ea8f4a>:0 
  at BepInEx.GUI.Patcher.LogSocketServer.SendLogsToClient () [0x000c0] in <badda5b0f29c42f7ad2b9e434751129a>:0 
  at BepInEx.GUI.Patcher.LogSocketServer.ServerThread () [0x0000c] in <badda5b0f29c42f7ad2b9e434751129a>:0
```

### Environment

```markdown
- OS: Windows 10 
- BepInEx: 5.4.19.0 (thunderstore version: 5.4.1903)
- Game: Risk of Rain 2
```

**Comment by IGP** [comment] 2022-04-21 18:53
I did a manual install of 5.4.19 and the logbook functioned. The issue may be specific to the package being served on thunderstore.io.

**Comment by bb010g** [comment] 2022-04-21 19:04
You can find the source for RoR2's BepInExPack at <https://github.com/risk-of-thunder/RoR2BepInExPack>; it performs game patches.

**Comment by ghorsington** [comment] 2022-04-21 19:49
Greetings!

The issue is caused by the game update introducing incompatibilities with existing mods. A workaround is now included as part of [RoR2BepInExPack](https://github.com/risk-of-thunder/RoR2BepInExPack) (courtesy of @xiaoxiao921). The said plugin is included in the new version of [BepInExPack for RoR2 5.4.1904](https://thunderstore.io/package/bbepis/BepInExPack/).

Closing this issue as it is now resolved by the third-party distribution. In the case of Risk of Rain 2, I suggest following the [RoR2 Modding Discord](https://discord.gg/5MbXZvd) for any game-specific modding support and updates.

**Closed by ghorsington** 2022-04-21 19:49 UTC
Labels: bug
