### ISSUE TITLE
New Valheim update broke BepIn

### ISSUE THREAD

**Issue by auddie2015** [BepInEx/BepInEx#247] opened 2021-05-12 13:11 UTC
As the title says, the game crashes on start with BepInEx installed after downloading an update this morning.

**Comment by ghorsington** [comment] 2021-05-12 13:14
Greetings!

This looks like a duplicate of #246 as you didn't provide any more information. As such, I'll close the issue as a duplicate.

If the issue at hand is not related to #246 at all, feel free to create a new ticket and provide relevant additional information. Better yet, use the `Bug report` template and fill out the information it asks.

**Closed by ghorsington** 2021-05-12 13:14 UTC
