### ISSUE TITLE
BepInEx Closing Out Steamworks

### ISSUE THREAD

**Issue by pootthedestroyer** [BepInEx/BepInEx#115] opened 2020-04-28 05:45 UTC
Upon opening the application (Risk of Rain 2,) a command window appears and BepInEx appears to be working normally, with no errors displayed. Then, for some reason, either it or Unity shuts down Steamworks, leaving the application closed, except for a consistent "phantom" in the Windows 10 Task Manager.

This error can be reproduced perfectly and infinitely. Open the game, watch the process, game gets closed.

Application: Risk of Rain 2 (through Steam.)

Plugins added:

AspectsFix.dll
BanditReloaded.dll
BossItemDrop.dll
DeathMarkFix.dll
OrderedItems.dll

Log pasted.
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/4543556/LogOutput.log)

**Comment by bbepis** [comment] 2020-04-29 03:39
Try and verify game integrity via Steam for the game.

If that doesn't fix the issue, please send me your `output_log.txt` file, which is located in `C:\Users\<user>\AppData\LocalLow\Hopoo Games, LLC\Risk of Rain 2\`

**Comment by pootthedestroyer** [comment] 2020-04-29 04:20
All files verified. Here's the requested log. A brief glance does suggest something is very wrong across the entire modding framework, but then again, I don't know much.

[output_log.txt](https://github.com/BepInEx/BepInEx/files/4549777/output_log.txt)

**Comment by bbepis** [comment] 2020-04-29 04:52
Just to make sure, you are using an up-to-date version of BepInExPack, right? It contains config options required to get risk of rain 2 working correctly

If you are, then there are some things I'd like you to test out:

- Disable the console in BepInEx/config/bepinex.cfg
- Temporarily remove all plugins and patcher plugins, and see if it launches. If it does, slowly add them back to see which one causes an issue (start with the R2API patcher and plugin)

**Comment by pootthedestroyer** [comment] 2020-04-29 08:17
The one I downloaded was updated 3 weeks ago; now that I'm here on github it doesn't look like there's anything more recent. Just to double check I downloaded the latest release version from github and did a copy/replace. I noticed that it achieved the exact same result... a bit faster.

Disabling Logging.Console stopped the cmd window from appearing but did not change the final outcome of opening the application.

Per your final request: unfortunately, I now cannot get this error to go away at all. I removed everything having to do with both BepinEx (including all plugins/patchers) and R2API) and the game still instantly closed after opening.

Sadly for me (but maybe happily for you,) a full clean reinstall of RoR2, pursuant to a Steam uninstall, did **not** resolve the issue.  Now my game will not work at all.

This bug report therefore may have shifted a bit... what, if anything, does BepinEx/R2API change in hidden crannies in my computer that a Steam uninstall might not actually catch?

**Comment by bbepis** [comment] 2020-04-29 09:31
> what, if anything, does BepinEx/R2API change in hidden crannies in my computer that a Steam uninstall might not actually catch?

All file modification/writing within plain BepInEx/R2API only happen inside the BepInEx folder. Mods might be a different story, but since BepInEx loads without patching / requiring any files to be modified, it's able to survive integrity verification for example.

If you want to purge everything related to BepInEx/R2API, then you'll need to remove the winhttp.dll and the BepInEx folder, as nothing short of an uninstall will remove it.

> Just to double check I downloaded the latest release version from github and did a copy/replace. I noticed that it achieved the exact same result... a bit faster.

I would suggest sticking with what's inside the thunderstore pack. They're not the exact same .dll files; the thunderstore variant has some dependencies updated as per request of the mod developers.

> UPDATE: I don't think it's a coincidence, but eventually I was able to get the game to start again and it reported a corrupted user profile. Given that any of the mods I installed could've corrupted said profile I know that that's not helpful, but it is very odd that I couldn't get the game to run and report that without multiple clean reinstalls and hunting down anything ROR2-related on my computer I could find to delete first.

If you haven't found it yet, your Risk of Rain 2 profile is located in `C:\Program Files (x86)\Steam\userdata\<steam user id>\632360\remote\UserProfiles`, which you can then delete.

Steam uninstall won't remove this as this is considered save data, and is kept within the steam cloud.

> Sadly for me (but maybe happily for you,) a full clean reinstall of RoR2, pursuant to a Steam uninstall, did not resolve the issue. Now my game will not work at all.

I would suggest checking out this discord server if you need additional risk of rain 2 modding tech support: https://discord.gg/5MbXZvd

As the issue is not specific to BepInEx, I will close the issue, but feel free to leave additional comments if something comes up.

**Closed by bbepis** 2020-04-29 09:31 UTC
Labels: bug
