### ISSUE TITLE
ArgumentException in preloader

### ISSUE THREAD

**Issue by ilducesaint** [BepInEx/BepInEx#75] opened 2019-05-05 01:05 UTC
I'm getting this error when executing Koikatsu

BepInEx 4.1.1.0 - Koikatu
[Message] Preloader started
[Fatal] Could not run preloader!
[Fatal] System.ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,System.String].Add (System.String key, System.String value) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.AssemblyPatcher.PatchAll (System.String directory, IDictionary`2 patcherMethodDictionary, IEnumerable`1 initializers, IEnumerable`1 finalizers) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.Preloader.Run () [0x00000] in <filename unknown>:0

can somple help me thanks!!

**Comment by denikson** [comment] 2019-05-05 07:14
Greetings!

This is related to #63. The issue is very likely caused by you having duplicate DLLs in `Koikatu_Data/Managed` folder. As a solution, I suggest to either

* Find and remove duplicate DLLs in the `Koikatu_Data/Managed`. Any DLLs that have a very similar name (i.e. `Assembly-CSharp.dll` and `Assembly-CSharp_backup.dll` or similar) are duplicates of each other. A more safe solution is to reinstall/restore from backup. **OR**
* Get the latest [HF Patch](https://www.patreon.com/posts/26388652) which contains BepInEx with this issue fixed.

As a side note, please use a proper issue template next time, so it's a bit simpler for us to understand your issue, what game version you're running and what the exact problem is. In addition, it helps us to keep track of different kinds of issues.

**Comment by denikson** [comment] 2019-05-27 18:12
Closing this because the issue is old. If you still have a problem, reply and I'll reopen the issue.

**Closed by denikson** 2019-05-27 18:12 UTC

**Comment by suampi18** [comment] 2019-07-04 01:21
I have the same problem
