### ISSUE TITLE
v5.3 Causes Unity Crash on game exit

### ISSUE THREAD

**Issue by wh0am15533** [BepInEx/BepInEx#139] opened 2020-09-18 22:50 UTC
**Describe the bug**
Game crash on exit. Example: Train Valley 2 build #164, with BepInEx v5.3, not an issue with earlier BepInEx versions. Seems to be something with the new Doorstop version. Using the older version.dll works fine. Using winhttp.dll causes the preloader to not run and you get preloader crash. Using version.dll you get game crash on exit, Mono complains about missing method. Revert to BepInEx v5.1 using same version.dll works fine.

**To Reproduce**
Open Game and close it. Unity Crash.

**Expected behavior**
Clean game exit

**Screenshots and logs**
[output_log.txt](https://github.com/BepInEx/BepInEx/files/5248555/output_log.txt)
[error.log](https://github.com/BepInEx/BepInEx/files/5248556/error.log)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Train Valley 2 Build #164
 - BepInEx version [e.g. 4.0]: v5.3

**Comment by denikson** [comment] 2020-09-19 17:01
Greetings!

Thank you for reporting this! I tested the game on build #169 and could not reproduce the issue. Build #164 uses Unity 2018 while the newer builds use Unity 2019. I suggest updating your game if possible.

However, I did manage to reproduce this on #164 and made a test fix. Please test the latest Bleeding Edge build:
https://builds.bepis.io/projects/bepinex_be/265/BepInEx_x64_a7a3274_5.3.0.265.zip

Please test it and check that this fixes the issue.

**Comment by wh0am15533** [comment] 2020-09-19 17:55
First, thanks for quick response! 

Ok, I tested this build (Still with TV2 Build #164) and it works... kinda. I've narrowed it done alittle further. I appears to be something with Logging to Console. If it's disabled, it works perfectly. If enabled, Crash. If I use ConsoleOut I get error about preloader couldn't run. If I use StandardOut I get a minidump, and if I use Auto, I get a Unity Crash. Changed Logging to Console back to false and runs perfectly. I'm sure your right in that it's the Unity version (2018 vs 2019) but I would still like to find this bug even if only for a personal build. I really like the backwards compatibility.

**Comment by denikson** [comment] 2020-09-19 18:06
Have you changed any BepInEx settings in any way from original?

In my tests (latest BE, build #164) just enabling console has everything working fine. In this case I'd assume it's more something to do with your setup rather than BepInEx. 

Here's the setup I currently have on build #164 (fresh download with DepotDownloader):
[BepInEx_TV2.zip](https://github.com/BepInEx/BepInEx/files/5250346/BepInEx_TV2.zip)

This is
* Current build from master (with config option to enable console)
* Latest verbose build of Doorstop from master
* Custom doorstop config to enable output log redirection (for convenience)

My testing procedure is as outlined in OP:
1. Launch the game and wait until it loads into main menu
2. Close the game (either via `Quit` or by closing the game window)

On my computer this does indeed cause a crash on 5.3 but the current master build I included with this message does work fine.

**Comment by wh0am15533** [comment] 2020-09-19 19:23
Interesting... Out of the box that build you just posted works perfectly, so I started comparing the previous one against this one. Doorstop is good. No errors in the log. 

Compared the BepInEx configs, the only I altered was turning console logging on/off. 

Starting fresh from the the above build, I started replacing the dll's with those from the BepInEx_x64_a7a3274_5.3.0.265 build, one-by-one. Everything worked until I replaced BepInEx.dll then the Unity Crash. So then I tested toggling console logging.

Here's the two packages. The only difference is the BepInEx.dll. 
1. If you take the Crashing package (BepInEx_x64_a7a3274_5.3.0.265) and run, it crashes.
2. Turn console logging off it works without crash.
3. Take the BepInEx.dll from the working package (The build above you posted) and put in place and run game. It works fine whether console logging is enabled or not.

[BepInEx-WORKING.zip](https://github.com/BepInEx/BepInEx/files/5250495/BepInEx-WORKING.zip)
[BepInEx-CRASH.zip](https://github.com/BepInEx/BepInEx/files/5250496/BepInEx-CRASH.zip)

**Comment by denikson** [comment] 2020-09-19 19:49
Thank you for the input!

Please test the new bleeding edge build:
https://builds.bepis.io/projects/bepinex_be/266/BepInEx_x64_a55939c_5.3.0.266.zip

This is an alternative fix that should potentially work better

**Comment by wh0am15533** [comment] 2020-09-19 19:57
Awesome, that one works PERFECTLY on both TV2 build 164 and 169, along with other games (i.e. Craftopia and Vaporum)! Great turn around time! 

Thank you for your time and efforts.

**Comment by denikson** [comment] 2020-09-19 19:59
Perfect, thanks for your time helping testing this and for your detailed initial report.

Going to close this issue as it's considered fixed now. If you have any other issues, feel free to create a new issue.

**Closed by denikson** 2020-09-19 19:59 UTC

**Comment by wh0am15533** [comment] 2020-09-19 20:03
Ok, closed and fixed. On a side note, it also works fine with Unity 5.7 and 2017.
