### ISSUE TITLE
BepInEx Problem with 真・痴漢の極み  from Beelzebub (ベルゼブブ) (System.Exception: The entrypoint type is invalid!)

### ISSUE THREAD

**Issue by Dragantis** [BepInEx/BepInEx#45] opened 2018-08-03 21:16 UTC
**Describe the bug**
I was trying to use BepinEx in 4.1 version with XUnity.AutoTranslator-BepIn-2.9.1 plugin to translate game 真・痴漢の極み from Beelzebub (ベルゼブブ) circle.

BepInEx does not work. There isn't any changes in game behavior with or without BepinEx. When I start game BepInEx create preloader_xx file.

**To Reproduce**
A short description of what you did for the bug to happen.
Installed BepInEx version 4.1 X86, started game once to create config, installed  XUnity.AutoTranslator-BepIn-2.9.1. Started the game.  

I also tried using BepInEx_x64_v4.1 but there is no respond at all, BepInEx does not even create config.

**Expected behavior**
I would like BepinEx to start with game and use XUnity.AutoTranslator-BepIn-2.9.1 plugin to translate ingame Japanse text in to English.

**Screenshots and logs**

```
Logs from preloader:
 BepInEx 4.1.0.0 - 真・痴漢の極み
[Message] Preloader started
[Fatal] Could not run preloader!
[Fatal] System.Exception: The entrypoint type is invalid! Please check your config.ini
  at BepInEx.Bootstrap.Preloader.PatchEntrypoint (Mono.Cecil.AssemblyDefinition& assembly) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.AssemblyPatcher.Patch (Mono.Cecil.AssemblyDefinition& assembly, BepInEx.Bootstrap.AssemblyPatcherDelegate patcherMethod) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.AssemblyPatcher.PatchAll (System.String directory, IDictionary`2 patcherMethodDictionary, IEnumerable`1 initializers, IEnumerable`1 finalizers) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.Preloader.Run () [0x00000] in <filename unknown>:0
```

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 真・痴漢の極み version:1.18.2.27
 - BepInEx version [e.g. 4.0]: BepInEx_x86_v4.1
- Windows 7 Ultimate x64

**Additional context**
I also tried BepInEx with 1room -家出少女- and it also does not work.
However I tried with Koikatu and COM3D2_1.10.1.010 and had no problems, everything was working right .

**Comment by softashell** [comment] 2018-08-04 06:06
For 1room -家出少女- you just need to change entry point assembly in config.ini from UnityEngine.dll to UnityEngine.CoreModule.dll and BepInEx itself will work and load plugins, but XUnity.AutoTranslator doesn't break lines in that game so most of the translated text will be cut off.

**Comment by midoukanehikaru** [comment] 2018-08-04 17:05
thanks, finally i can make plugin work with those games

but 1room have an error, day count turn into this: <size=28>Day</size>2<size=28>(日)あと6日</size>
this make game won't load event, anyway to fix this ?

**Comment by denikson** [comment] 2018-08-04 17:12
Greetings!

It seems you have found an answer to the issue: newer Unity games require to change the entrypoint assembly to `UnityEngine.CoreModule.dll` (via `entrypoint-assembly` option inside `config.ini`).  
As of right now, there is no proper guide on how to configure the entrypoint: that will be done soon.

I will close the issue once I have the entrypoint configuration guide up on the wiki.

***

@midoukanehikaru Do you use XUnity.AutoTranslator? It sounds like the issue is related to that, not BepInEx. You might want to find the repository you downloaded AT from and create an issue there. I suggest trying to downloaded the most up-to-date fork at [XUnity-Development/XUnity.AutoTranslator](https://github.com/XUnity-Development/XUnity.AutoTranslator). If that doesn't help, you can create an issue in there.

**Comment by denikson** [comment] 2018-08-08 12:09
And the wiki is now updated with some basic info [on how to port BepInEx to different games](https://github.com/BepInEx/BepInEx/wiki/Porting-BepInEx).

Closing the issue, since the problem is resolved and an appropriate wiki page has been added.

**Closed by denikson** 2018-08-08 12:09 UTC
