### ISSUE TITLE
Use BepInEx without installing any mods, unable to enter the game black screen

### ISSUE THREAD

**Issue by FurryRbl** [BepInEx/BepInEx#346] opened 2021-12-21 12:01 UTC
### What happened?

Use BepInEx without installing any mods, unable to enter the game black screen
May have nothing to do with mono.dll
If you don't use BepInEx, the black screen will not appear when the game starts
![SharedScreenshot](https://user-images.githubusercontent.com/61524717/146926298-8335c600-643c-4619-898e-92159fb28e5b.jpg)

[output_log.txt](https://github.com/BepInEx/BepInEx/files/7755113/output_log.txt)

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
BepInEx:
[Message:   BepInEx] BepInEx 5.4.17.0 - oriDE (4/28/2016 4:56:24 AM)
[Info   :   BepInEx] Running under Unity v5.3.2.9582331
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.17.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Warning:  HarmonyX] AccessTools.Property: Could not find property for type UnityEngine.Application and name isBatchMode
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] Object::FindAnyObjectOfType<MonoBehaviour> ()
[Error  : Unity Log] Object::FindAnyObjectOfType<MonoScript> ()




dnSpy:
19:20:39.727 Mono path[0] = 'C:/Users/VupRb/Desktop/Game/Ori_DE_Mod/oriDE_Data/Managed'
19:20:39.767 Mono path[1] = 'C:/Users/VupRb/Desktop/Game/Ori_DE_Mod/oriDE_Data/Mono'
19:20:39.768 Mono config path = 'C:/Users/VupRb/Desktop/Game/Ori_DE_Mod/oriDE_Data/Mono/etc'
19:20:39.769 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\mscorlib.dll'
19:20:39.814 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\MonoMod.Utils.dll'
19:20:39.822 oriDE.exe (Unity: Unity Root Domain): 已加载 'data-056FE168'
19:20:39.827 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\MonoMod.RuntimeDetour.dll'
19:20:39.829 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\0Harmony.dll'
19:20:39.831 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\System.dll'
19:20:39.833 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\Mono.Cecil.Rocks.dll'
19:20:39.835 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\Mono.Cecil.Pdb.dll'
19:20:39.837 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\Mono.Cecil.Mdb.dll'
19:20:39.839 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\Mono.Cecil.dll'
19:20:39.840 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\System.Core.dll'
19:20:39.842 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\BepInEx.dll'
19:20:39.844 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\BepInEx.Preloader.dll'
19:20:42.439 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:42.440 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:42.486 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\BepInEx\core\HarmonyXInterop.dll'
19:20:42.999 引发异常: 'System.IO.EndOfStreamException' in mscorlib.dll
19:20:43.001 其他信息: Failed to read past end of stream.
19:20:43.420 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:43.422 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:43.438 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:43.440 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:43.453 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:43.456 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:43.958 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:43.959 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:43.972 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:43.975 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:44.042 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\Mono.Security.dll'
19:20:44.046 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\System.Configuration.dll'
19:20:44.062 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\System.Xml.dll'
19:20:45.092 引发异常: 'System.Configuration.ConfigurationErrorsException' in System.Configuration.dll
19:20:45.095 其他信息: Unrecognized element 'trace'.
19:20:45.423 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:45.424 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:45.436 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:45.437 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:45.451 引发异常: 'System.NotSupportedException' in mscorlib.dll
19:20:45.453 其他信息: Custom attributes on a ParamInfo with member System.Reflection.Emit.DynamicMethod are not supported
19:20:45.733 引发异常: 'System.ArgumentNullException' in mscorlib.dll
19:20:45.735 其他信息: Argument cannot be null.
19:20:47.552 oriDE.exe (Unity: Unity Root Domain): 已加载 'data-0942C020'
19:20:49.734 引发异常: 'System.MissingMethodException' in mscorlib.dll
19:20:49.738 其他信息: Cannot find the requested method.
19:20:49.797 引发异常: 'System.Reflection.TargetInvocationException' in mscorlib.dll
19:20:49.799 其他信息: Exception has been thrown by the target of an invocation.
19:20:51.059 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\Assembly-CSharp-firstpass.dll'
19:20:51.064 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\Assembly-CSharp.dll'
19:20:51.090 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\UnityEngine.UI.dll'
19:20:51.094 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\UnityEngine.Networking.dll'
19:20:51.097 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\SteamworksManaged.dll'
19:20:51.104 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\LibTessDotNet.dll'
19:20:51.125 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\LostPolygon.SpriteSharp.Clipper.dll'
19:20:51.149 oriDE.exe (Unity: Unity Root Domain): 已加载 'C:\Users\VupRb\Desktop\Game\Ori_DE_Mod\oriDE_Data\Managed\J2i.Net.XInputWrapper.dll'
19:20:52.354 线程 0x80e4ed8 已退出，返回值为 0 (0x0)。
19:20:53.748 线程 0x80e4bb8 已退出，返回值为 0 (0x0)。
19:20:55.760 线程 0x80e4c80 已退出，返回值为 0 (0x0)。
19:20:57.763 线程 0x80e4d48 已退出，返回值为 0 (0x0)。
19:20:59.761 线程 0x80e4898 已退出，返回值为 0 (0x0)。
19:21:01.762 线程 0x80e4708 已退出，返回值为 0 (0x0)。
19:21:03.761 线程 0x80e47d0 已退出，返回值为 0 (0x0)。
19:21:05.761 线程 0x80e4640 已退出，返回值为 0 (0x0)。
19:21:07.761 线程 0x80e44b0 已退出，返回值为 0 (0x0)。
19:21:09.763 线程 0x80e43e8 已退出，返回值为 0 (0x0)。
19:21:11.762 线程 0x80e4320 已退出，返回值为 0 (0x0)。
19:21:13.013 '[0x17F0] oriDE.exe' 程序已退出，返回值为 0 (0x0)。
```

### Environment

```markdown
- OS: Windows10 Pro 21H1
- BepInEx: 5.4.17.0
- Game: Ori and the Blind Forest
```

**Comment by ghorsington** [comment] 2021-12-21 13:21
Greetings!

This issue seems indeed peculiar. Judging by the errors, there may be issues with using the normal `System.Reflection.Emit` namespace for generating dynamic methods. BepInEx perhaps didn't pick this up didn't automatically switch to the cecil backend.

As such, try opening `BepInEx/config/BepInEx.cfg`, finding option `HarmonyBackend` and changing its value to `cecil` (the default value should be `auto`).

Also, mind posting the game's output log? dnSpy doesn't seem to catch all the logs. One way to obtain the output log is to open `doorstop_config.ini` and set `redirectOutputLog` to `true`. That way the `output_log.txt` should appear next to the game executable.

**Comment by FurryRbl** [comment] 2021-12-21 13:35
> 问候！
> 
> 这个问题似乎的确奇特。 判断的错误，可能存在问题的使用正常的 `System.Reflection.Emit` 名字空间的用于生成的动态方法。 BepInEx也许没有选择这不会自动开关给塞西尔的后端。
> 
> 因此，试图打开 `BepInEx/config/BepInEx.cfg`，找到选项 `HarmonyBackend` 并改变它的价值 `cecil` (默认值应 `auto`).
> 
> 此外，记帐游戏的输出记录？ dnSpy似乎并没有捕捉到所有的日志。 一个方法得到输出日志是打开 `doorstop_config.ini` 并设置 `redirectOutputLog` 要 `true`. 那样的 `output_log.txt` 应该出现在旁边的游戏可执行的。
[output_log.txt](https://github.com/BepInEx/BepInEx/files/7755662/output_log.txt)

**Comment by ghorsington** [comment] 2021-12-21 13:40
Okay, this looks much better. The game uses an old Unity version which might need additional configuration.

I suggest checking out the [troubleshooting steps for Unity 5](https://docs.bepinex.dev/articles/user_guide/troubleshooting.html#unity-5-and-older) and changing the entry point in configuration. I think changing it to `MonoBehaviour` might help with the `The referenced script on this Behaviour is missing` error.

**Comment by FurryRbl** [comment] 2021-12-21 13:55
> 

The problem has been resolved, but it may be temporary,
thanks.

[output_log.txt](https://github.com/BepInEx/BepInEx/files/7755777/output_log.txt)

**Comment by ghorsington** [comment] 2021-12-21 14:16
Looks like the issue was about the entry point. This is a permanent solution, because different games need different BepInEx configuration to run properly.

As for

```

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Behaviour:set_enabled (bool)
  at CameraPostProcessing.ApplyCameraSettings (.CameraSettings cameraSettings) [0x00000] in <filename unknown>:0 
  at CameraPostProcessing.Apply () [0x00000] in <filename unknown>:0 
  at UberPostBloomAnimator.RestoreToOriginalState () [0x00000] in <filename unknown>:0 
  at UberPostBloomAnimator.OnDisable () [0x00000] in <filename unknown>:0 
 ```

It could be caused by the OriModsApi that you try to use. You can also try editing the entry point a bit more to see if it helps. Either way, I'll likely mark this ticket as resolved because the problem was in the default configuration not working for this old game.

**Comment by ghorsington** [comment] 2022-02-13 08:02
Closing issue as it looks like it was resolved by config change

**Closed by ghorsington** 2022-02-13 08:02 UTC
Labels: needs-replication, error
