### ISSUE TITLE
BepInEx 4 run failed

### ISSUE THREAD

**Issue by magicdmer** [BepInEx/BepInEx#36] opened 2018-07-16 15:26 UTC
**preloader_20180716_232431_103.log**
BepInEx 4.0.0.0 - Koikatu
[Message] Preloader started
[Fatal] Could not run preloader!
[Fatal] System.Exception: Cyclic Dependency
  at BepInEx.Common.Utility.<TopologicalSort>g__Visit|9_0[AssemblyDefinition] (Mono.Cecil.AssemblyDefinition node, BepInEx.Common.<>c__DisplayClass9_0`1& ) [0x00000] in <filename unknown>:0 
  at BepInEx.Common.Utility.<TopologicalSort>g__Visit|9_0[AssemblyDefinition] (Mono.Cecil.AssemblyDefinition node, BepInEx.Common.<>c__DisplayClass9_0`1& ) [0x00000] in <filename unknown>:0 
  at BepInEx.Common.Utility.<TopologicalSort>g__Visit|9_0[AssemblyDefinition] (Mono.Cecil.AssemblyDefinition node, BepInEx.Common.<>c__DisplayClass9_0`1& ) [0x00000] in <filename unknown>:0 
  at BepInEx.Common.Utility.<TopologicalSort>g__Visit|9_0[AssemblyDefinition] (Mono.Cecil.AssemblyDefinition node, BepInEx.Common.<>c__DisplayClass9_0`1& ) [0x00000] in <filename unknown>:0 
  at BepInEx.Common.Utility.TopologicalSort[AssemblyDefinition] (IEnumerable`1 nodes, System.Func`2 dependencySelector) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.AssemblyPatcher.PatchAll (System.String directory, IDictionary`2 patcherMethodDictionary, IEnumerable`1 initializers, IEnumerable`1 finalizers) [0x00000] in <filename unknown>:0 
  at BepInEx.Bootstrap.Preloader.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by denikson** [comment] 2018-07-16 15:35
Greetings!

Before posting issues, please refer to the [contribution guide](https://github.com/BepInEx/BepInEx/blob/master/CONTRIBUTING.md#bug-reports) to create a more descriptive issue report.  

If reading is not your cup of tea, please use one of the **issue templates** that you only need to fill out. For instance, you can use the *Bug report* template in this case.

Everything considered, we cannot really help until you provide more information about the game, what plug-ins/tools you have installed and what you tried to do prior the error.

That said, this looks very similar to #35 -- if you have IPA installed on top of BepInEx, please remove IPA. 
If you were upgrading from BepInEx 3.x, please follow the [migration guide](https://github.com/BepInEx/BepInEx/wiki/Migration#migration-from-previous-versions-of-bepinex).


I'm marking this issue as a duplicate of #35 and closing it for the time being. Please create a new issue and provide more information.

**Closed by denikson** 2018-07-16 15:35 UTC
