### ISSUE TITLE
Requesting visibility into what settings exist in the ConfigFile

### ISSUE THREAD

**Issue by GreyHak** [BepInEx/BepInEx#203] opened 2021-03-08 04:36 UTC
I have a mod which uses BepInEx that I would like to update.  I need to convert, for example, a single boolean config setting into two new ones.  This means I need to detect that the old configuration is in use, and use it to create the new one.  It looks like BepInEx.Configuration.ConfigFile doesn't give me any means to do this.

I would like to be able to see if a ConfigDefinition is present in the OrphanedEntries.  This would let me see its value, promote it and remove it, but the key point here is that it would let me use its value to create the new config settings.  Without knowing if the ConfigDefinition is present in the OrphanedEntries, I can see its value and remove it, but I don't know if I'm just getting the default value.

An alternative solution would be, when I Bind to a ConfigDefinition, please let me know if it was new, or pulled from the OrphanedEntries.

Great library.  Thank you for all your hard work!

**Comment by notpeelz** [comment] 2021-03-09 03:06
Related to #187

**Comment by ghorsington** [comment] 2021-03-09 06:32
Greetings!

Thanks for the suggestion. Seeing as this is more or less a duplicate of #187, I'm going to close it. Feel free to comment/add your suggestions in that ticket instead.

**Closed by ghorsington** 2021-03-09 06:32 UTC
