### ISSUE TITLE
I get these on startup of HS2

### ISSUE THREAD

**Issue by Bar2co** [BepInEx/BepInEx#382] opened 2022-03-17 19:10 UTC
### What happened?

For example:

[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly ConfigurationManager, Version=16.4.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <7ba07f088431485bb722f3b3373e87ee>:0
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <4c7064deb21340f6835f67d7a798b5ef>:0
[output_log.txt](https://github.com/BepInEx/BepInEx/files/8289445/output_log.txt)

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
Log is too long apparently so:
[output_log.txt](https://github.com/BepInEx/BepInEx/files/8289445/output_log.txt)
```

### Environment

```markdown
- OS: Windows 10 21H2
- BepInEx: 5.4.18.0
- Game: HoneySelect2
```

**Comment by ghorsington** [comment] 2022-03-17 19:21
Greetings!

As apparent from the message, these are warnings rather than errors. The exception is usually caused by outdated plugins, bugs in plugins or general incompatibility between plugins and code. Because this particular exception does not necessarily prevent the game from working, they are not marked as errors. 

I suggest reviewing the plugins you have installed and upgrade/disable them as necessary. In general, these warnings are meant to inform the plugin developer of potential problems in their plugin and to suggest users to report the issue to plugin creators.

**Closed** 2022-06-02 19:27 UTC
Labels: needs-replication, error
