### ISSUE TITLE
First run of  run_bepinex.sh results in unhandled exception

### ISSUE THREAD

**Issue by Nicholasmanente25** [BepInEx/BepInEx#251] opened 2021-05-15 01:40 UTC
Hello! I'm trying to install BepInEx 5.4.11 to ubuntu server 20.04 where I am running a Valheim Dedicated server (the game server works no problem) and am getting the following error (also in photo):

Fallback handler could not load library /home/administrator/steamcmd/valheim_server_Data/Mono/▒▒▒m▒U/mono/aot-cache/amd64/BepInEx.Preloader.dll.so
Got image: 0x55b76dea2780

Unhandled Exception:
System.MissingMethodException: void System.IO.File.WriteAllText(string,string)
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: void System.IO.File.WriteAllText(string,string)

![Error](https://user-images.githubusercontent.com/32181764/118344503-5c67d900-b4fc-11eb-9586-32058d2796c1.png)

I have the latest system updates, GCC version 10.2, have extracted the files for unix into the game's folder, and modified the shell script with the valheim executable name. I've been trying to figure this out all day and haven't gotten far so any insight would be greatly appreciated!

I've also added 3 screenshots below of my shell scrip if needed
![SH 1](https://user-images.githubusercontent.com/32181764/118344606-0182b180-b4fd-11eb-984d-fc87e2b0eafc.png)
![SH2](https://user-images.githubusercontent.com/32181764/118344608-021b4800-b4fd-11eb-91a8-9e2e8de605e1.png)
![SH 3](https://user-images.githubusercontent.com/32181764/118344607-021b4800-b4fd-11eb-9fe3-b06e68535feb.png)

**Comment by Windows10CE** [comment] 2021-05-15 02:00
Hello! This is mostly due to the fact the Valheim ships with stripped DLLs, which is explained in https://github.com/NeighTools/UnityDoorstop/issues/10. If this is the case, using https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/, which includes unstripped versions of these DLLs specific to Valheim for BepInEx to use, should resolve the issue.

**Comment by ghorsington** [comment] 2021-05-15 04:48
Greetings!

This looks like a duplicate of #182. As Windows10CE mentioned, you should either include unstripped mono DLLs yourself and configure BepInEx to use them or use [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) which comes preconfigured with necessary launch scripts for both game client and server.

If you have any further issues, feel free to create a new ticket.

**Closed by ghorsington** 2021-05-15 04:48 UTC
