### ISSUE TITLE
preloader error

### ISSUE THREAD

**Issue by A1A2A3A4A5Y6** [BepInEx/BepInEx#282] opened 2021-07-24 00:51 UTC
**Describe the issue**

Problems in games that use "beplnEx" to apply mode

**To Reproduce**

If you download "beplnex" and insert the file into the "game.exe" location and run it, the "preloader.txt" file is not applied and is created

**Expected behavior**

**Screenshots and logs**

[preloader_20210724_094227_256.log](https://github.com/BepInEx/BepInEx/files/6871679/preloader_20210724_094227_256.log)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 
 - BepInEx version [e.g. 4.0]: 
x64_5.4.12.0

**Additional context**

**Comment by ManlyMarco** [comment] 2021-07-24 09:29
Try v5.4.13

**Comment by ghorsington** [comment] 2021-07-25 16:57
Greetings!

This is a duplicate of #279. Please update to BepInEx 5.4.13 as Marco suggested.

If you have any further issues, feel free to create a new issue ticket.

**Closed by ghorsington** 2021-07-25 16:57 UTC
