### ISSUE TITLE
Unable to find method SendPreWillRenderCanvases in [UnityEngine.UIModule.dll]UnityEngine.Canvas

### ISSUE THREAD

**Issue by Vertux** [BepInEx/BepInEx#249] opened 2021-05-13 07:30 UTC
**Describe the bug**
Since the latest Valheim update 0.153.2 Valheim crashes with this error:
```
[Message:   BepInEx] BepInEx 5.4.11.0 - valheim
[Info   :   BepInEx] Running under Unity v2019.4.24.6137584
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [Clock Mod 1.1.1]
[Info   :   BepInEx] Loading [Time Mod 0.5.2]
[Info   :   BepInEx] Loading [FarmGrid 0.2.0]
[Info   :   BepInEx] Loading [BetterUI 1.6.4]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 1.1.0]
[Info   :   BepInEx] Loading [Trash Items Mod 1.2.3]
[Info   :Trash Items Mod] TrashItems Loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 05/13/2021 09:17:54: Starting to load scene:start

[Error  : Unity Log] Unable to find method SendPreWillRenderCanvases in [UnityEngine.UIModule.dll]UnityEngine.Canvas
```
**Desktop (please complete the following information):**
 - Game and game version: Valheim v0.153.2
 - BepInEx version: v5.4.11.0

**Comment by ghorsington** [comment] 2021-05-13 07:33
Greetings!

Thank you for the logs and for providing extensive information!

This is a duplicate of #246 and can be fixed by updating the unstripped Unity DLLs using the updated BepInExPack for Valheim (or grabbing the updated Unity DLLs from it).

Closing this down as it is a duplicate. If you have any further issues, feel free to create a new ticket.

**Closed by ghorsington** 2021-05-13 07:33 UTC

**Comment by Vertux** [comment] 2021-05-13 07:38
@ghorsington 
Sorry, I have overlooked it, thank you.
