### ISSUE TITLE
keep having issue with valheim mistlands issue with unity log error 

### ISSUE THREAD

**Issue by eesab** [BepInEx/BepInEx#531] opened 2022-12-18 05:44 UTC
### What happened?

 whenever  i start one of my worlds, i get sent to my spawn, float as my camera spins unable to move. here is the error message i keep getting: https://i.imgur.com/kFff2nA.png

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
[Cte EMU Faa es -SIE CECE. PEER rey ay Ci

[Error : Unity Log] MissingMethodexception: StatusEffect SEMan.AddStatusEffect(string,bool)
Serato

(wrapper dynamic-method) Player .DMD<Player:: :OnSpawned>(Player)

Clee naar ence Rc eee ee co EM rea SC tae)

Cle eae en ere cL e NCL reser ne Col era)

Game.FixedUpdate () (at <@353@7@6@cbb4b3eb916cd82ebd8e490>: 0)
```

### Environment

```markdown
- OS: windows  10
- BepInEx: 5.4.1901
- Game: latest build of valheim
```

**Comment by ghorsington** [comment] 2022-12-18 20:12
Greetings!

Based on your information, the issue appears to be caused by some plugin. Since you didn't provide the full log, it's impossible to say what plugin exactly is causing the issue. I suggest first updating all plugins, as most plugins broke after the last Valheim update. If updating doesn't help, disable your plugins until you find the problematic one. If the console moves too fast, refer to `BepInEx/LogOutput.log` for the entire log, which contains information on what plugins are being loaded.

Either way, this is a plugin-specific issue and thus not actionable by us. If you need help with Valheim-specific plugins, you can try asking for help in [Valheim modding Discord](https://discord.gg/RBq2mzeu4z).

Closing this issue as non-actionable. Feel free to create a new issue should you have other problems.

**Closed by ghorsington** 2022-12-18 20:12 UTC
Labels: invalid, game-specific

**Comment by eesab** [comment] 2022-12-18 22:55
i figured it out, it was a broken mod called passive forsaken powers.

**Comment by Recon419A** [comment] 2023-01-29 09:46
@eesab thank you for reporting back, you saved me a lot of hassle with my own modded setup.
