### ISSUE TITLE
Bepinex patched on the game Gorilla Tag (Might be unintended or intentional)

### ISSUE THREAD

**Issue by zelay2008** [BepInEx/BepInEx#529] opened 2022-12-16 01:57 UTC
### What happened?

Title.

### Steps to reproduce

1. Install Bepinex
2. Install any other mods
3. They aren't functioning due to Bepinex being patched.

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: Windows
- BepInEx: 5.4.21
- Game: Gorilla Tag
```

**Comment by Windows10CE** [comment] 2022-12-16 07:12
What exactly do you mean by patched?

**Comment by zelay2008** [comment] 2022-12-16 16:03
> What exactly do you mean by patched?

Excuse me for the late reply.
Patched as in non functional. It appears some changing of in-game code or removal of some files caused it to cease to function on the game.

**Comment by ghorsington** [comment] 2022-12-18 20:04
Greetings!

It looks like the latest version of the game comes with stripped game assemblies which prevent BepInEx and plugins from working. For more information on the issue and how to fix it, check out this guide: ["Stripped Unity games and how to unstrip them"](https://hackmd.io/@ghorsington/rJuLdZTzK)

After stripping the game assemblies according to the "How to unstrip my game?" guide (I did the "dirty but basic way" just for testing, but the "clean and more involved" should work just as file), BepInEx loads up normally:

![image](https://user-images.githubusercontent.com/13762037/208316733-178d941c-f83e-47a0-b161-e278aa2983b1.png)

Unfortunately, there is nothing we can do about this on BepInEx side, as the problem is with how the game packages its assemblies. Therefore I'm closing this as non-actionable on our side. You can ask the game developers not to strip the game assemblies in their game, but the only workaround is the one mentioned above.

**Closed by ghorsington** 2022-12-18 20:04 UTC
Labels: bug

**Comment by cracker345** [comment] 2023-11-01 14:39
> ### What happened?
> Title.
> 
> ### Steps to reproduce
> 1. Install Bepinex
> 2. Install any other mods
> 3. They aren't functioning due to Bepinex being patched.
> 
> ### BepInEx Distribution
> Stable from GitHub
> 
> ### Log outputs
> _No response_
> 
> ### Environment
> ```
> - OS: Windows
> - BepInEx: 5.4.21
> - Game: Gorilla Tag
> ```

how the fuck do i delete it?

**Comment by MATTHEWFRATTO** [comment] 2024-03-05 23:18
it makes my player model bug out so I can't play the game

**Comment by jordan190786** [comment] 2025-03-14 04:53
for me bepinex works fine :)
