### ISSUE TITLE
Koikatsu won't launch with BepInEX 4.0

### ISSUE THREAD

**Issue by Enoah35** [BepInEx/BepInEx#37] opened 2018-07-19 03:14 UTC
**Describe the bug**

The InitSetting.exe was giving an error of my graphic card driver (nvspcap64.dll error) so I update it since it was a while before I did it. Now it gives no errors but the game simply won't launch if the winhttp.dll is present in the game directory. The koikatsu I have installed is 64 bits. 

**To Reproduce**
A short description of what you did for the bug to happen.

I have used BepInEx 3.2 without issues and followed the instructions given. Deleted the 3 dlls on all 3 folders (Koikatsu_Data, Charastudio_Data, and in KoikatsuVR_Data) and restored the UnityEngine.dll.bak to UnityEngine.dll). I have depeted the patcher exe from the game root. The game simply will not run. It does run when removing the winhttp.dll. I did give permision to the files of the downloaded content too.

**Expected behavior**

According to the description, the game should run normally and it should create a config.ini file on the BepInEx folder. I have not even reached to this point.

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

Can't provide anything since I cannot run the game.

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Koikatsu 3.0
 - BepInEx version [e.g. 4.0]:  4.0

**Additional context**

Putting the 32bit version of the winhttp.dll, the game will launch but thats because BepInEx is not loaded. It does not create any file. I am not sure what I am doing it wrong.

**Comment by denikson** [comment] 2018-07-19 06:18
Greetings! Thank you for this quite extensive report!

Have you tried running the game without the launcher (i.e. running directly `Koikatu.exe`)?

If that does not help, could you try running with the debug version of `winhttp.dll`:

[**winhttp_debug.zip**](https://github.com/BepInEx/BepInEx/files/2208491/winhttp_debug.zip)

When you run the game with this DLL, you should see `doorstop.log` created in the game's folder. Could you send the log here?

**Comment by pgdhr** [comment] 2018-07-19 15:08
Hi, this problem also appear in my Koikatsu.

**Description**
BepInEx v3.2 can work well, but when i updated it to v4.0 it can't work.
I thought i might have some mistake when  updated BepInEx to v4.0 so i delete the whole game folder and reinstall the game then put BepInEx v4.0 in it , that time there didn't have any plugins in game folder such as IPA,but v4.0 still can't work.It even didn't create config.ini in Koikatsu\BepInEx folder.

**Behavior when run Koikatsu.exe**
If i put x64 winhttp.dll in game folder, game not start and will appear an error info window said i lost some .dll file about vc++ such as api-ms-win-crt-studio-l1-1-0.dll.
If i put x86 winhttp.dll in game folder,game will normally start,but not run with BepInEx v4.0 as i just said.

And if i put winhttp.dll in winhttp_debug.zip you provided, it also can't start game and said i lost .dll file, but it is VCRUNTIME140d.dll.


So i guess if it is some problem caused by my pc's VC++ Redistributable Package?I have installed Microsoft Visual C++ Redistributable 2012,2013 and 2015 in my pc.

My pc's system is windows 8.1 x64, game is Koikatsu, if there are any other info you need please ask. 

Waitting for your reply, thanks!

**Comment by denikson** [comment] 2018-07-19 16:08
@pgdhr Thank you for the info!

To make sure, please download and (at least try to) install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

Then, please try out this slightly edited version:

[**winhttp_verbose_release.zip**](https://github.com/BepInEx/BepInEx/files/2210751/winhttp_verbose_release.zip)

Again, you should see `doorstop.log` pop up when the game launches.

**Comment by pgdhr** [comment] 2018-07-19 16:21
@denikson Thanks for reply, i will try it tomorrow,and tell you the result :)

**Comment by pgdhr** [comment] 2018-07-20 01:57
@denikson Finally, i solved my problem by install  Visual C++ Redistributable 2017.

I don't know if VC++ 2017 is necessary for BepInEx v4.0, but in my pc it is. I hope this question can be helpful for your  development :)

**Comment by Enoah35** [comment] 2018-07-20 03:07
Hello. I have done the steps as you have indicated but to no avail. here are the results of the tests.

By using the debug version it will give back with an error as stated by pgdhr. (error VCRUNTIME140d.dll and another one). I have re-installed the 2015, 2017 of the redistributable and still its the same deal.

Now using the verbose version of the dll will give back with a log file. No matter which version of Redistributable I use it gives back the same log. 

Doorstop started!
DLL Path: D:\????\WINHTTP.dll
Doorstop DLL Name: WINHTTP
EAT pointer name: WINHTTP.ownMonoJitInitVersion
Config; Target assembly: BepInEx\core\BepInEx.dll
Config; Fallback DLL: 
Doorstop enabled!
Loading Mono!
Finding mono.dll from D:\????\Koikatu_Data\Mono\mono.dll
Hooking into mono_jit_init_version
Loading assembly: BepInEx\core\BepInEx.dll
Invoking method!

The log ends there. The ???? is a JP character. Not sure if that is the problem. Any other suggestions?

**Comment by Enoah35** [comment] 2018-07-20 03:35
Update. Using the debug dll with the needed DLLs installed on system32 stops the error, but gives back the same result as using other dlls. The game does not  launch. Will attatch the log just in case, but the content is the same as described above.
[doorstop.log](https://github.com/BepInEx/BepInEx/files/2212353/doorstop.log)

**Comment by denikson** [comment] 2018-07-20 05:59
Aha! That actually does help a whole lot!

Release 4.0 is known to fail if the path contains Japanese characters.
Try installing the latest build from master:

[**BepInEx_x64_4f48d5c.zip**](https://github.com/BepInEx/BepInEx/files/2212629/BepInEx_x64_4f48d5c.zip)

Just move the files to the game's folder and overwrite when asked.

**Comment by Enoah35** [comment] 2018-07-20 22:09
Hello. The lastest build did the trick and it created the files needed. the game launches as it should be. Thank you for all the support.

**Comment by denikson** [comment] 2018-07-21 07:02
Perfect!

For other people who experience a similar issue: please wait until the next release of BepInEx.

To mitigate the issue until the next release, you can do one of the following:

1. Build BepInEx from the latest source
2. ~~Download the bleeding edge build~~ Not available yet, we're working on this
3. Temporarily change the path to the game. Remove all "exotic" characters, and only leave basic ANSI characters in.

Again, thank you all for the reports. Closing this issue because the problem is resolved and there is nothing to add to it.

**Closed by denikson** 2018-07-21 07:02 UTC
