### ISSUE TITLE
BepinEX pack prevents Risk of Rain 2 achievement manager from working

### ISSUE THREAD

**Issue by doctorthoss** [BepInEx/BepInEx#405] opened 2022-04-23 00:40 UTC
### What happened?

no achievements can be unlcocked while running mods on the current version of RoR2 as it breaks AchievementManager. many people can be found talking about this online, here's just one example https://www.reddit.com/r/RiskofRain2_Mods/comments/u7l2qu/unable_to_unlock_achievements_while_using_mods/

### Steps to reproduce

meet the requirements to unlock a character/item/achivement while running bepinexpack 

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: Windows 10 
- BepInEx: 5.4.1905
- Game: risk of rain 2
```

**Comment by ghorsington** [comment] 2022-04-23 11:01
Greetings!

The main problem caused by the game update was fixed in [RoR2BepInExPack](https://github.com/risk-of-thunder/RoR2BepInExPack) that's included in the BepInExPack for Valheim (see #404 for details). The fixed plugin is now included in [BepInExPack](https://thunderstore.io/package/bbepis/BepInExPack/) 5.4.1904 and newer. If you are still experiencing issues, please do the following:

* Make sure you have properly installed the latest version of BepInExPack. If in doubt, reinstall.
* Run the game without any mods first. **Some mods still need to be updated to fix their issues with achievements.**

Finally, if you still are encountering issues, please include the full logs with your issue (game's `output_log.txt` or BepInEx's `LogOutput.log`); otherwise, we will not be able to help you. Additionally, consider joining [Risk of Rain 2 Modding Discord](https://discord.gg/5MbXZvd) for any updated and technical support, as they can provide RoR2-specific modding help rather than just a general-purpose BepInEx help.

For now, I am closing this issue as a duplicate of #404 and for lacking additional information. Feel free to create a new issue (or, better, consider joining the RoR2 Modding Discord) if you can provide more information.

**Closed by ghorsington** 2022-04-23 11:01 UTC
Labels: bug
