### ISSUE TITLE
[Koikatu] Game refuses to load BepInEx/Doorstop and any attached features

### ISSUE THREAD

**Issue by AnnoyingParrot** [BepInEx/BepInEx#86] opened 2019-08-03 22:38 UTC
Hey folks. I've been struggling with this problem for the past week or so and am running out of ideas on how to debug it.

**Describe the bug**

The base game runs fine on its own, but the moment I add BepInEx's winhttp.dll to its root directory, it ceases to operate in any capacity. Checking my Process Explorer and Resource Manager, I can see that, at most, Koikatu.exe appears in memory for half a second before vanishing.

**To Reproduce**
A short description of what you did for the bug to happen.

I attempted to run the game's main client, Koikatu.exe. (InitSetting.exe functions as normal -- to an extent. I'll explain that in the extra content section.)

**Expected behavior**

I'd normally expect the game to attempt to run or at least throw an error of some kind.

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

There are no thrown errors. I have attempted to use the debug version of winhttp, which successfully generates a doorstop.log file, but the file doesn't contain any information at all and is entirely empty.

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Koikatu 5.1
 - BepInEx version [e.g. 4.0]: 4.1.1 and higher

**Additional context**

For starters, I have been referring extensively to the thread for issue#37 (https://github.com/BepInEx/BepInEx/issues/37), as my issue at least appeared to be similar on the surface, however I have not had any luck thus far. The path does not contain non-ANSI characters, and my Visual C++ Redistributable has not assisted regardless of version. I also attempted to use the latest build of BepInEx (both the one in the thread as well as the nightly one currently on the releases page, 5.0) to no avail.

Running InitSetting.exe opens the launcher as expected, and its functionality for the most part is normal. However, if I click any of the three "Start [exe}" items, the launcher closes (as I would expect it should) and then... nothing occurs.

To try and isolate the issue, I tried to operate a clean installation of just BepInEx (i.e., reinstalled the base game and all DLC, then went and downloaded _only_ BepInEx's files and tested the game with and without them); while installed, the described problem occurs, while without it, the game loads as normal. For the sake of being complete, I then attempted to use the 32-bit version of BepInEx (my PC has a 64-bit Windows 7 OS); using this instead of the 64-bit version, the base game loaded as normal, but none of the translations, mods, or plugins loaded when I proceeded try adding them back. As such, I'm somewhat confident the issue lies with either the winhttp.dll file or one of BepInEx's core files.

I should probably mention that this is my first time trying to install this game, and so I can't say that I've ever had a (modded) functional Koikatu before.

Any assistance is greatly appreciated. Thanks a bundle.

**Comment by denikson** [comment] 2019-08-04 06:34
Greetings!

Thank for all this information: you clearly have done some extensive debugging, and all this information is very helpful.

The debug build of Doorstop you mentioned is very old; it might be already outdated.
Please try this latest build of BepInEx 5 + debug Doorstop:

[BepIn5_cecil.zip](https://github.com/BepInEx/BepInEx/files/3464598/BepIn5_cecil.zip)

Make sure you delete any files of previous BepInEx installations you have (`winhttp.dll`s, `BepInEx` folders...). If this works, you should get Doorstop logs (`.log` files starting with `doorstop_` prefix).

**Comment by AnnoyingParrot** [comment] 2019-08-04 07:21
Thanks for the reply!

The build you suggested did result in.. something. doorstop_1564902519.log was generated, but its only contents are, "Doorstop started!" The file contains no further information.

However, this time, at the time I ran the executable, it did actually throw an error. The contents of the error message were as follows:
"The application was unable to start correctly (0xc0000005). Click OK to close the application."
From what I'm gathering, this error is... an access violation of some sort? I'm not sure I'm finding a consensus of what this code's significance is. Has this been encountered in the given context before?

**Comment by denikson** [comment] 2019-08-04 07:36
Thanks for the info!

This actually narrows down the potential issue quite a bit.
Could you try replacing `version.dll` with this version and see if the new generated log gives any more info?
[version.zip](https://github.com/BepInEx/BepInEx/files/3464642/version.zip)

I suggest deleting the previous log to prevent confusion.

**Comment by AnnoyingParrot** [comment] 2019-08-04 07:44
Thanks again for the reply.

The new dll generated doorstop_1564904360.log (I deleted the prior log to ensure that no mixup occurred), the contents of which were the same as before: "Doorstop started!". Also, similarly, the executable threw 0xc0000005 again. Am I missing something here?

**Comment by denikson** [comment] 2019-08-04 07:54
This indeed seems like an interesting issue. Do you have any Anti-Virus software?

Here's another edit where it will show message boxes instead of writing to a file. Perhaps it might give more messages than before.
[version.zip](https://github.com/BepInEx/BepInEx/files/3464656/version.zip)

Meanwhile, I'll try to set up a Windows 7 VM and see if I can somehow reproduce the error.

**Comment by AnnoyingParrot** [comment] 2019-08-04 08:08
Okay, that one was far more eventful. I had quite a few popups thrown at me. I copy-and-pasted their contents to a text file as they appeared/I dismissed them, and the result is as follows:

Doorstop started!
App dir: %S
Working dir: %S
STDOUT handle at %p
Pointer to GetFinalPathNameByHandleA %p
STDOUT handle path: %s
DLL Path: %S
EXE Path: %S
Doorstop DLL Name: %S
Doorstop DLL Name: %S
Looking for original DLL from %S
Looking for original DLL from %S
Config; Target assembly: %S
Doorstop enabled!
No UnityPlayer.dll; using EXE as the hook target.
Installing IAT hook
Hook installed!
Got mono.dll at %p
Loaded all mono.dll functions
Starting mono domain
STDOUT handle at %p
STDOUT handle path: %s
Assembly dir: %s
Loading assembly: %s
Invoking method!

After this, the popups ceased. I saw the command console rapidly open and close, but no further action ensued.

To answer your first question: At the moment I am running Malwarebytes 3.8.3. It automatically initiated a trial of its premium version when I last updated it, so its real-time protection feature is available and enabled, but it has not been returning any positives as far as Koikatu is concerned.

However, before this, I had an enterprise edition of Sophos Anti-Virus issued by my university (from which I have since graduated). The very first time I attempted to run the client's executable, Sophos quarantined it. I ended up removing Sophos from my computer this past Thursday and then doing a clean installation of the game to try again. That was the point where my endeavors began.

**Comment by denikson** [comment] 2019-08-04 08:16
I'm really sorry you have to go through this. It seems like there is something 3rd party that causes this. Though it might as well be something really Windows specific.

Would you mind testing this one out? It should have now more detailed messages (albeit still as message boxes, since for some reason it doesn't like to write them to a file in your case).
[version.zip](https://github.com/BepInEx/BepInEx/files/3464673/version.zip)

**Comment by AnnoyingParrot** [comment] 2019-08-04 08:23
This one seems more substantial. The contents of the popups were as follows:

Doorstop started!
App dir: C:\illusion\Koikatu
Working dir: C:\illusion\Koikatu
STDOUT handle at 0000000000000000
Pointer to GetFinalPathNameByHandleA 000000007711B9C0
STDOUT handle path: 
DLL Path: C:\illusion\Koikatu\VERSION.dll
EXE Path: C:\illusion\Koikatu\Koikatu.exe
Doorstop DLL Name: VERSION
Looking for original DLL from C:\illusion\Koikatu\VERSION_alt.dll
Looking for original DLL from C:\Windows\system32\VERSION.dll
Config; Target assembly: C:\illusion\Koikatu\BepInEx\core\BepInEx.Preloader.dll
Doorstop enabled!
No UnityPlayer.dll; using EXE as the hook target.
Installing IAT hook
Hook installed!
Got mono.dll at 000007FEC9F50000
Loaded all mono.dll functions
Starting mono domain
STDOUT handle at 0000000000000000
STDOUT handle path: 
Assembly dir: C:\illusion\Koikatu\Koikatu_Data\Managed
Loading assembly: C:\illusion\Koikatu\BepInEx\core\BepInEx.Preloader.dll
Invoking method!

At the end, I once again saw the command console for all of a tenth of a second.

**Comment by denikson** [comment] 2019-08-04 08:39
This is indeed peculiar, as it would imply that Doorstop works fine, while something happens on BepInEx side. Or that Doorstop works when I enable logging via message boxes instead of writing to a file...

I made an edit to BepInEx and included normal Doorstop.
[bepin5_test2.zip](https://github.com/BepInEx/BepInEx/files/3464690/bepin5_test2.zip)

If this works, you should get `bepin_log.txt`. If this fails, could you try using `version.dll` that I sent in the last message (with the message boxes)?

**Comment by AnnoyingParrot** [comment] 2019-08-04 08:46
Thanks for sticking with me this far.

The BepInEx build you provided generated bepin_log.txt, the contents of which are as follows:

Entered the preloder!
Loaded ENV vars!
Preloader path: C:\illusion\Koikatu\BepInEx\core
In preload main!
BepInEx path: C:\illusion\Koikatu\BepInEx
Running preloader!
Allocating console!
Console allocated!

I was hesitant to perform further action as your provided files seem to have had the initially desired effect. Should I proceed with your other suggestions at this time? (e.g. disable antivirus real-time protection, and/or use the prior version.dll)

**Comment by denikson** [comment] 2019-08-04 08:48
Thanks for all this info; this now clearly points to something happening in BepInEx instead of Doorstop.

You can try disabling AV, but no need to use the prior `version.dll` since we now determined that it's not the culprit here.

I'll try to add some additional logging to see where it exactly fails.

**Comment by AnnoyingParrot** [comment] 2019-08-04 08:51
I ran the build with Malwarebytes disabled. The resulting bepin_log.txt contained the same information as before.

**Comment by denikson** [comment] 2019-08-04 08:55
So that means that at least MBytes doesn't interfere with it directly.

Would you mind testing this version? This should give now more logging.
[bepin5_test3.zip](https://github.com/BepInEx/BepInEx/files/3464709/bepin5_test3.zip)

**Comment by AnnoyingParrot** [comment] 2019-08-04 08:57
This is turning into quite the train wreck. I sincerely appreciate your patience and dedication.

The log's contents are as follows:

Entered the preloder!
Loaded ENV vars!
Preloader path: C:\illusion\Koikatu\BepInEx\core
In preload main!
BepInEx path: C:\illusion\Koikatu\BepInEx
Running preloader!
Allocating console!
Console allocated!
Trying to shim Harmony if needed
Applying Unity patches

**Comment by denikson** [comment] 2019-08-04 09:00
Okay, this finally gives something concrete.

Go to `BepInEx\config\BepInEx.cfg`, find and set

```ini
ShimHarmonySupport = true
```

Try running again. If that fails too in a similar way as before, set it back to `false` and instead set

```ini
ApplyRuntimePatches = false
```

**Comment by AnnoyingParrot** [comment] 2019-08-04 09:10
Setting ShimHarmonySupport to true resulted in the following bepin_log.txt:

Entered the preloder!
Loaded ENV vars!
Preloader path: C:\illusion\Koikatu\BepInEx\core
In preload main!
BepInEx path: C:\illusion\Koikatu\BepInEx
Running preloader!
Allocating console!
Console allocated!
Trying to shim Harmony if needed

Returning ShimHarmonySpport to false and then setting ApplyRuntimePatches to false caused two things. Firstly, it generated the following bepin_log.txt:

Entered the preloder!
Loaded ENV vars!
Preloader path: C:\illusion\Koikatu\BepInEx\core
In preload main!
BepInEx path: C:\illusion\Koikatu\BepInEx
Running preloader!
Allocating console!
Console allocated!
Trying to shim Harmony if needed
Applying Unity patches
Adding Trace as log source
Init preloader log listener
Changing title
Writing title to console!
Polling info about current environment
Writing info to console
Starting preloading!

Secondly, the game loaded, but it appears to be the base game. The command console also opened and remained open for the duration of Koikatu.exe's session. I've attached a screenshot of the console's contents below.

![Screenshot - 2019_08_04 , 5_03_36](https://user-images.githubusercontent.com/53666026/62421825-f9ce8180-b675-11e9-8721-6f8e3315cff0.png)

**Comment by denikson** [comment] 2019-08-04 09:18
Interesting! As it appears right now, disabling memory patching seems to fix the issue!

That said, it's interesting why that is caused. What's more, I'm afraid that if you start installing plugins, it might crash again if said plugin tries to do memory patching too.

For now, I suggest installing some plugins and testing if they work out. I'll get back to this issue when I come up with something reasonable to try.

**Comment by AnnoyingParrot** [comment] 2019-08-04 09:29
I apologize. I should have mentioned that the screenshot above was with a plugin inserted to test whether or not I was only getting the base game. This seems to be the case. No mods, translations, or plugins are successfully executing when I run the game -- I just get the base game each time. 

For consistency, the bepin_log.txt generated from a plugin-less startup is as follows:

Entered the preloder!
Loaded ENV vars!
Preloader path: C:\illusion\Koikatu\BepInEx\core
In preload main!
BepInEx path: C:\illusion\Koikatu\BepInEx
Running preloader!
Allocating console!
Console allocated!
Trying to shim Harmony if needed
Applying Unity patches
Adding Trace as log source
Init preloader log listener
Changing title
Writing title to console!
Polling info about current environment
Writing info to console
Starting preloading!

The (base) game launches and the console appears; the console contains the same information as my last comment, but without the missing dependency error.

**Comment by denikson** [comment] 2019-08-04 09:41
Oh yeah, you probably have a bunch of BepInEx 4 plugins, right? Since this is BepInEx 5, you need a helper patcher that makes them loadable.  
Place the DLL into `BepInEx/patchers`.

[BepInEx.BepIn4Patcher.zip](https://github.com/BepInEx/BepInEx/files/3464760/BepInEx.BepIn4Patcher.zip)

Then make sure you have your BepInEx 4 plugins in `BepInEx` folder.

This kind of seems like an issue with something preventing memory manipulation, which is needed by Harmony -- a runtime patching library BepInEx uses.

In theory, if this is indeed an issue with something preventing memory manipulation, the patcher should crash.

**Comment by AnnoyingParrot** [comment] 2019-08-04 09:50
With the patcher installed, running Koikatu.exe causes the command console to appear momentarily, spit out some returns that are too fast for my eye to catch, and then close. The game's client itself does not open. If it helps, I've attached the bepin_log as well.

Entered the preloder!
Loaded ENV vars!
Preloader path: C:\illusion\Koikatu\BepInEx\core
In preload main!
BepInEx path: C:\illusion\Koikatu\BepInEx
Running preloader!
Allocating console!
Console allocated!
Trying to shim Harmony if needed
Applying Unity patches
Adding Trace as log source
Init preloader log listener
Changing title
Writing title to console!
Polling info about current environment
Writing info to console
Starting preloading!

I also made an exclusion rule in Malwarebytes for the entire Koikatu directory and attempted again. I did not notice a difference.

**Comment by denikson** [comment] 2019-08-04 09:57
Sorry to hear that. Given all this, I can so far conclude that something is trying to prevent the game's memory from being modified at all. It might be some program, it might be something else.  
Unfortunately, at the moment I don't see a way to find out the culprit reliably other by starting and removing/disabling programs that somehow could try and protect the memory.

I'll try installing the AVs you have and had, so it might become apparent then. Something is clearly preventing the game from modifying itself, which is an important part of how BepInEx functions.

If you do want to test out, I suggest turning `ApplyRuntimePatches` to `true` and then trying until you can get the game to boot. If the game boots with `ApplyRuntimePatches=true`, it means Harmony managed to access and edit the memory successfully.

Sorry again for not being able to come up with a reasonable solution right now. At least now we know what part of BepInEx does cause the problem.

**Comment by AnnoyingParrot** [comment] 2019-08-04 10:03
I'm sincerely grateful for all your input thus far. I really mean it. 

I'm going to sleep on this for the time being. I have a sneaking suspicion that Sophos has some kind of remnant on my computer, as I was not able to uninstall it through normal means; the instance of the software I had was administered by the university, and I was never given a Tamper Protection code, so I had no way to disable it normally. As such, I had to change some of its registry values to disable Tamper Protection, then boot in Safe Mode and delete its directories in Program Files/Program Files (x86)/ProgramData. Needless to say, my removal method was likely sloppy at best. 

I'll come back to this tomorrow.

**Comment by AnnoyingParrot** [comment] 2019-08-04 21:36
Okay... I did a thorough search of anything that was tied to Sophos and deleted quite a few drivers and other older temp files, but I didn't discover any hidden executables or dlls. Nevertheless, the deletion of the aforementioned files did not result in any changes. Going through my installed program list and disabling (what I thought might be) relevant software didn't seem to be assisting in this endeavor, either.

I then began playing with different setups utilizing BepInEx. I've found that the game boots successfully while using BepInEx 3.2 and it seems to retain its functionality. I then attempted to install BepisPlugins 11.1 and found that they caused the game to crash. I tested each dll individually with the game and discovered that the following three dlls all cause the game to fail:
ExtensibleSaveFormat.dll
ResourceRedirector.dll
SliderUnlocker.dll

I also attempted to install KK_BecomeTrap 1.1.1 with all but the above three components of BepisPlugins inserted (and KKAPI, which is required for the mod; the game functions with it installed). I found that the dll from that mod causes the following console error, both with and without the presence of the "mods" directory in the game's root:
![Screenshot - 2019_08_04 , 17_24_55](https://user-images.githubusercontent.com/53666026/62429516-abed6400-b6dd-11e9-8f5b-9a17e7204608.png)

I do not at this time know the significance of these findings, but I wanted to share in case someone else can interpret it.

**Comment by AnnoyingParrot** [comment] 2019-08-05 05:29
I've attempted to fiddle with file and directory permissions and ownership. I granted full control of the Koikatu directory to all users on the system, as well as all of the BepInEx dlls and xmls. I changed ownership of the aforementioned files from User to Administrator, as well. All of the above have not proved fruitful. 

I attempted a build with BepInEx 5.0, BepisPlugins 11.1, KKAPI, and the BepIn4Patcher.dll that you provided some time back. As-is, the console opens and closes rapidly and the game does not boot. If I modify ApplyRuntimePatches within BepInEx.cfg to false and with the console enabled, the game boots, but I receive the following error from the console:

System.TypeLoadException: A type load exception has occurred.
  at BepInEx.BepIn4Patcher.BepIn4Patcher+<get_TargetDLLs>d__17.MoveNext () [0x00000] in <filename unknown>:0 
  at BepInEx.Preloader.Patching.AssemblyPatcher.PatchAndLoad (System.String directory) [0x00000] in <filename unknown>:0 
  at BepInEx.Preloader.Preloader.Run () [0x00000] in <filename unknown>:0 

I suppose all of this is really just reaffirming that some component of BepInEx is unable to write to memory, but perhaps the above information might prove helpful in some other context? I don't know. I'm just about out of ideas on this one.

**Comment by denikson** [comment] 2019-08-05 07:35
I've tested the AVs you mentioned by downloading MBytes and Sophos. Even though Sophos was jut a Home edition, it did block Koikatu from running at all when tried with BepInEx, which MBytes seems to not have effect on it at all.

This kind of leads me to believe something is still blocking some important places in memory from being overwritten. Unfortunately I really cannot come up with any different reason why it would fail.  

For now my last idea is for you to try out our hardpatcher for BepInEx 4:
[bepin4_hard.zip](https://github.com/BepInEx/BepInEx/files/3466389/bepin4_hard.zip)

To use this, remove BepInEx 5 completely (along with doorstop config and `version.dll`). Then put the files from the archive in the game directory and run `BepInEx.Patcher.exe` (in the game directory). After it runs and exists, run Koikatsu.

The main difference between this and Doorstop one is that BepInEx doesn't use Harmony at all. Morevoer, it uses older Harmony in case Harmony 2 (which is shipped with BepInEx 5) is the real culprit here.

IMPORTANT: When you want to delete this version of BepInEx, go to `Koikatu_Data\Managed` and restore `UnityEngine.dll.bak` into `UnityEngine.dll` (it's automatically created by the patcher).

If the plugins fail, it will more or less undeniably show that it's Harmony and its memory patching that causes the problem.

**Comment by AnnoyingParrot** [comment] 2019-08-05 18:22
Ugh!! There is a reason why a friend of mine and I have dubbed Sophos to be a "yandere AI".

Thank you so much for all of your help. I did not expect this to turn into as big of a mess as it did.

I tried running the game with the hard patcher. While BepInEx functioned, the moment I began adding plugins the game indeed crashed at startup.

**I have now confirmed that Sophos was the culprit.** I re-installed Sophos, then used Total Uninstaller to be absolutely sure I was removing every possible trace of it. The game now functions with mods and plugins! Hurray!
...Except I seem to have sacrificed some component of my network adapters in the process of removing Sophos. The computer in question is now completely unable to operate any network-based applications, and I cannot System Restore it back as, for some reason, I no longer seem to have any restore points available. I'll have to look into reinstalling the operating system somehow.

Nonetheless, that problem is now on my hands -- you have done a magnificent job assisting me through all of this, and I can't thank you enough for your help. Cheers.

**Comment by denikson** [comment] 2019-08-05 18:28
You're most welcome! Glad to hear you finally managed to resolve the issue. It is rather unfortunate you had to sacrifice your working OS installation and so much time. Nonetheless, we all learned something new here.

I hope you will be able to fix your computer's problem successfully. When you do, I suggest removing the hardpatched BepInEx as I instructed and instead use BepInEx 4 from the releases page on this project.

If you do happen to get any further issues related to BepInEx, feel free to create a new issue ticket. I'm closing this one, as the main issue can be considered resolved.

**Closed by denikson** 2019-08-05 18:28 UTC
