### ISSUE TITLE
Typing in overlay still controls game

### ISSUE THREAD

**Issue by WillWilli** [BepInEx/BepInEx#520] opened 2022-11-27 23:06 UTC
### What happened?

Typing anywhere in the overlay still controls the game behind it. Is there any way to override this behaviour? 
Thanks.

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
N/A
```

### Environment

```markdown
- OS: Win11
- BepInEx: 5.4.21.0
- Game: PlateUp!
```

**Comment by ghorsington** [comment] 2022-11-28 05:09
Greetings!

BepInEx itself does not include any overlays. Instead, it seems you might have some plugin installed with this particular issue. Unfortunately, I cannot tell which plugin it is because log output is missing.

Nevertheless, the issue is not related to core BepInEx but rather the plugin that adds the overlay you're referring to. I suggest testing which plugin it is and reporting the issue to the relevant project. Closing this issue as not actionable.

**Closed by ghorsington** 2022-11-28 05:09 UTC
Labels: needs-replication, error
