### ISSUE TITLE
5.3 throws System.ArgumentNullException exception in Mac Subnautica

### ISSUE THREAD

**Issue by gbooker** [BepInEx/BepInEx#147] opened 2020-11-01 15:07 UTC
**Describe the bug**
Pretty much as the title describes.  The exception is thrown and no patchers/plugins are loaded.  However 5.2 does work as expected.

**To Reproduce**
- Install 5.3 per the instructions for a Steam game on the Mac (https://bepinex.github.io/bepinex_docs/master/articles/advanced/steam_interop.html?tabs=tabid-2) into Subnautica
  - Alternatively, try running the script provided by a user to install QModManager: https://gist.github.com/slheavner/7b95d9e652b8b9df7b5f5b72c50754b3
- Launch game from Steam
- See that no patchers/plugins are operational but a `preloader_….log` file is created

**Expected behavior**
Patchers/plugins are loaded.

**Screenshots and logs**
```
System.TypeInitializationException: The type initializer for 'BepInEx.Unix.UnixStreamHelper' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: libraryPtr
  at MonoMod.Utils.DynDll.InternalTryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x0000d] in <24039fd716e544118da35de096f1f4ab>:0 
  at MonoMod.Utils.DynDll.TryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x00000] in <24039fd716e544118da35de096f1f4ab>:0 
  at MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00117] in <24039fd716e544118da35de096f1f4ab>:0 
  at MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00000] in <24039fd716e544118da35de096f1f4ab>:0 
  at BepInEx.Unix.UnixStreamHelper..cctor () [0x00046] in <46489213e37f47fe96b58c45ec0cec51>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at BepInEx.Unix.LinuxConsoleDriver.Initialize (System.Boolean alreadyActive) [0x00029] in <46489213e37f47fe96b58c45ec0cec51>:0 
  at BepInEx.ConsoleManager.Initialize (System.Boolean alreadyActive) [0x00033] in <46489213e37f47fe96b58c45ec0cec51>:0 
  at BepInEx.Preloader.Preloader.Run () [0x00005] in <f9454f44494642d6aa1808eb7ec9b41e>:0  
```

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Subnautica July 2020 65786
 - BepInEx version [e.g. 4.0]: 5.3

**Additional context**
As a side note, I've somehow gotten Steam running with the envs `DOORSTOP_INITIALIZED` and `DOORSTOP_PROCESS_PATH` set.  Perhaps it was one of the times that I ran the script on the CLI and it launched Steam to launch the app?  Anyway, I've added lines to unset these envs to the script out of safety.

**Comment by denikson** [comment] 2020-11-01 15:14
Greetings!

Thanks for the extensive report!  
To me it seems like it could be caused by some problems with `libc.so` (and `libc.so.6`) resolving.

Please try the Bleeding Edge build #257:

https://builds.bepis.io/projects/bepinex_be/257/BepInEx_unix_6d5d2fe_5.3.0.257.zip

You should be able to simply replace your current `BepInEx/core` folder with one provided in the ZIP (of course, make a backup of the folder you have currently).

**Comment by gbooker** [comment] 2020-11-01 15:22
And now that you mention it, I realized that I had forgotten to mention that I tried BE 279 🤦.  I had the same result with it.  I tried 257 just now and it gave me an identically looking preloader log (with some pointers being different):
```
System.TypeInitializationException: The type initializer for 'BepInEx.Unix.UnixStreamHelper' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: libraryPtr
  at MonoMod.Utils.DynDll.InternalTryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x0000d] in <24039fd716e544118da35de096f1f4ab>:0 
  at MonoMod.Utils.DynDll.TryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x00000] in <24039fd716e544118da35de096f1f4ab>:0 
  at MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00117] in <24039fd716e544118da35de096f1f4ab>:0 
  at MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00000] in <24039fd716e544118da35de096f1f4ab>:0 
  at BepInEx.Unix.UnixStreamHelper..cctor () [0x00046] in <a595709ab7994c25baf10f3a6810144e>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at BepInEx.Unix.LinuxConsoleDriver.Initialize (System.Boolean alreadyActive) [0x00007] in <a595709ab7994c25baf10f3a6810144e>:0 
  at BepInEx.ConsoleManager.Initialize (System.Boolean alreadyActive) [0x00033] in <a595709ab7994c25baf10f3a6810144e>:0 
  at BepInEx.Preloader.Preloader.Run () [0x00005] in <03189bc9b809432b807e0fbd2f4093b9>:0 
```

I also forgot to mention that the machine is running 10.15.7 and I have some things installed with homebrew like `mono` should that make any difference (though it seems like it shouldn't but throwing that out there just in case).

**Comment by denikson** [comment] 2020-11-01 15:41
This is indeed interesting.  
Please try to replace MonoMod DLLs that are in `BepInEx/core` with these two:

[MonoMod_Edit.zip](https://github.com/BepInEx/BepInEx/files/5471210/MonoMod_Edit.zip)

This ideally should give a different error.

Also, can you check that `libSystem.dylib` exists in `/usr/lib` (or any other dylibs that have `libSystem` in it -- a simple `ls` might be enough). I'm assuming you're using macOS judging by your initial message. Do correct me if I'm wrong.

**Comment by gbooker** [comment] 2020-11-01 22:26
> This is indeed interesting.

If only the problem were boring and trivial 😉.

> Please try to replace MonoMod DLLs that are in `BepInEx/core` with these two:
> 
> [MonoMod_Edit.zip](https://github.com/BepInEx/BepInEx/files/5471210/MonoMod_Edit.zip)
> 
> This ideally should give a different error.

It occurred to me that I'm not certain if you want me to make this modification to 5.2 or to 5.3.  So here's the results of both.

5.2 substituting the supplied dlls:
```
System.TypeInitializationException: The type initializer for 'BepInEx.Unix.UnixStreamHelper' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: libraryPtr
  at MonoMod.Utils.DynDll.InternalTryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x0000d] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at MonoMod.Utils.DynDll.TryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x00000] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00117] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00000] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at BepInEx.Unix.UnixStreamHelper..cctor () [0x00046] in <1300b7f86d5e4b2a86eca7fae164eee3>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at BepInEx.Unix.LinuxConsoleDriver.Initialize (System.Boolean alreadyActive) [0x00029] in <1300b7f86d5e4b2a86eca7fae164eee3>:0 
  at BepInEx.ConsoleManager.Initialize (System.Boolean alreadyActive) [0x00033] in <1300b7f86d5e4b2a86eca7fae164eee3>:0 
  at BepInEx.Preloader.Preloader.Run () [0x00005] in <91abbf6e809d40a89ed3956a49dc1f99>:0 
```

5.3 substituting the supplied dlls:
```

System.TypeInitializationException: The type initializer for 'BepInEx.Unix.UnixStreamHelper' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: libraryPtr
  at MonoMod.Utils.DynDll.InternalTryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x0000d] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at MonoMod.Utils.DynDll.TryGetFunction (System.IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x00000] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00117] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00000] in <a871522addfb4f9a8d653ed3c95ca279>:0 
  at BepInEx.Unix.UnixStreamHelper..cctor () [0x00046] in <46489213e37f47fe96b58c45ec0cec51>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at BepInEx.Unix.LinuxConsoleDriver.Initialize (System.Boolean alreadyActive) [0x00029] in <46489213e37f47fe96b58c45ec0cec51>:0 
  at BepInEx.ConsoleManager.Initialize (System.Boolean alreadyActive) [0x00033] in <46489213e37f47fe96b58c45ec0cec51>:0 
  at BepInEx.Preloader.Preloader.Run () [0x00005] in <f9454f44494642d6aa1808eb7ec9b41e>:0 
```

They look the same to me though.

> Also, can you check that `libSystem.dylib` exists in `/usr/lib` (or any other dylibs that have `libSystem` in it -- a simple `ls` might be enough).

```
% ll /usr/lib/libSystem*
-rwxr-xr-x  1 root  wheel    81K Sep 21 19:29 /usr/lib/libSystem.B.dylib
lrwxr-xr-x  1 root  wheel    17B Oct 31  2019 /usr/lib/libSystem.dylib -> libSystem.B.dylib
% ll /usr/lib/libsystem*
-rwxr-xr-x  1 root  wheel   109K Sep 21 19:29 /usr/lib/libsystemstats.dylib
```
I figured you meant the first but included the second (different case of `system`) just in case.

> I'm assuming you're using macOS judging by your initial message. Do correct me if I'm wrong.

Correct.  MacOS Catalina 10.15.7

**Comment by denikson** [comment] 2020-11-02 19:51
Interesting, on a quick glance there is nothing that would cause this.

Can you try replacing MonoMod DLLs now with this version:

[MM_Logging.zip](https://github.com/BepInEx/BepInEx/files/5477625/MM_Logging.zip)

Please try with BepInEx 5.3. If this works, it should generate a file named `mmresolve.log` next to the executable (on macOS it's either next to the `.app` folder or somewhere inside the `.app` itself -- you might need to have to search for it in there).
Please send over the log you get.

If there is no such log, one possibility could be that perhaps there is some other MonoMod DLL collection that might interfere. This could be the case depending on what installation of BepInEx you had initially. I'm basing these debug steps off the fact that you're just using pure BepInEx without some old pre-BepInEx version of QModManager.

**Comment by gbooker** [comment] 2020-11-02 20:37
> Can you try replacing MonoMod DLLs now with this version: … Please try with BepInEx 5.3.

Tried and got these:

[mmresolve.log](https://github.com/BepInEx/BepInEx/files/5477872/mmresolve.log)
[preloader_20201102_143023_691.log](https://github.com/BepInEx/BepInEx/files/5477873/preloader_20201102_143023_691.log)

They were both alongside the `.app`.

> This could be the case depending on what installation of BepInEx you had initially. I'm basing these debug steps off the fact that you're just using pure BepInEx without some old pre-BepInEx version of QModManager.

For reference, the first ever BepInEx I tried was 5.3.  I only went to trying 5.2 when I kept getting the errors in this GHI.  I had tried the latest BE build and the one you linked as well.
Prior to that I was using QModManager 3.3 but I blew it away prior to trying BepInEx by deleting the entire `Subnautica.app/Contents/Resources/Data/Managed` directory and having Steam restore those files.  Just to confirm, before conducting this test I had Steam verify the local files and they all passed.

**Comment by denikson** [comment] 2020-11-02 20:51
> Tried and got these

Thanks for these, this looks fairly helpful. Could you repeat the process one more time with these DLLs:

[MM_Debug2.zip](https://github.com/BepInEx/BepInEx/files/5477932/MM_Debug2.zip)

Please remove the existing log file first so that it will generate a fresh one.

>  Just to confirm, before conducting this test I had Steam verify the local files and they all passed.

Perfect, in that case it should give pretty reliable results.  

It seems like there's an issue on MonoMod side not handling macOS properly when it comes to resolving native libraries. Very peculiar behaviour from macOS side, but this final test should be enough for me to make an experimental fix. Thanks for sticking with me on this one, it would've been really hard to debug this myself as I don't have access to macOS 10.15.

**Comment by gbooker** [comment] 2020-11-02 20:56
OK, here are the next set of files:

[preloader_20201102_145437_035.log](https://github.com/BepInEx/BepInEx/files/5477973/preloader_20201102_145437_035.log)
[mmresolve.log](https://github.com/BepInEx/BepInEx/files/5477975/mmresolve.log)

**Comment by denikson** [comment] 2020-11-02 21:14
Thank you for the log.

This is indeed a very peculiar issue. Here's a first attempt at a fix.

[MM_Fix_1.zip](https://github.com/BepInEx/BepInEx/files/5478064/MM_Fix_1.zip)

I preserved the logging, so please do send the new resolve log that gets created.

**Comment by gbooker** [comment] 2020-11-02 21:19
Got both logs again:

[preloader_20201102_151845_030.log](https://github.com/BepInEx/BepInEx/files/5478087/preloader_20201102_151845_030.log)
[mmresolve.log](https://github.com/BepInEx/BepInEx/files/5478088/mmresolve.log)

**Comment by denikson** [comment] 2020-11-02 21:27
Here are two different variations at once

[MM_Fix_2.zip](https://github.com/BepInEx/BepInEx/files/5478117/MM_Fix_2.zip)
[MM_Fix_3.zip](https://github.com/BepInEx/BepInEx/files/5478118/MM_Fix_3.zip)

I'm fairly certain the _3 option will work (or at least produce a different error, but _2 is likely a better solution overall so I hope it works too.

**Comment by gbooker** [comment] 2020-11-02 21:35
\o/ both worked, at least enough to not give a preloader log and to load up QModManager which loaded up a mod that modifies the list of saved games (b/c that's a very quick test).  With 2 I did enter a game and confirms several more of the mods under QModManager worked so no reason to think that any don't.

Resolve log from 2: 
[mmresolve_2.log](https://github.com/BepInEx/BepInEx/files/5478153/mmresolve_2.log)

Resolve log from 3:
[mmresolve_3.log](https://github.com/BepInEx/BepInEx/files/5478154/mmresolve_3.log)

**Comment by denikson** [comment] 2020-11-02 21:43
Perfect, thank you for helping with debugging this issue!

Here's a final version that's cleaned up and unnecessary logging removing

[MM_Fix_final.zip](https://github.com/BepInEx/BepInEx/files/5478199/MM_Fix_final.zip)

Please verify that this still works. I'll make a PR to MonoMod with the fix ASAP and ask the maintainer to make a new release so we can make use of it in BepInEx. In the meantime, you can use the fixed DLLs just fine.

**Comment by gbooker** [comment] 2020-11-02 21:57
Yep, still works.

**Comment by denikson** [comment] 2020-11-02 21:58
> Yep, still works.

Thanks for the info.

I'll close this issue once the MonoMod fix has been PRd into MonoMod and it's in use in BepInEx master

**Comment by denikson** [comment] 2020-11-06 12:58
Updated MonoMod is now being used on master

**Closed by denikson** 2020-11-06 12:58 UTC
Labels: bug, external

**Comment by gbooker** [comment] 2020-11-06 16:11
Thank you for resolving this.  I'll be sure to test out the next release when it comes out to make sure but in the mean time the modified binaries you gave me earlier continue to work well.

**Comment by gbooker** [comment] 2020-11-21 03:24
So I finally gave this a shot and got a failure:
```
[Error  :   BepInEx] Failed to run Finalizer of QModManager.QModPluginGenerator: System.MissingMethodException: System.Reflection.Emit.DynamicMethod HarmonyLib.Harmony.Patch(System.Reflection.MethodBase,HarmonyLib.HarmonyMethod,HarmonyLib.HarmonyMethod,HarmonyLib.HarmonyMethod,HarmonyLib.HarmonyMethod)
  at BepInEx.Preloader.Patching.AssemblyPatcher.FinalizePatching () [0x0001e] in <70eb20a48c62434c9a238efcdc2da63d>:0 
```
This leads me to conclude that the problem is with QModManager and not with BepInEx (if I'm wrong I can open a new GHI).  So now I need to wait for them to update their code to work with 5.4 and give it another go then.  In the mean time I'll continue to use the patched version as that continues to work with QModManager.

**Comment by denikson** [comment] 2020-11-21 06:20
Dist this happen on 5.4.1? Can you provide the full log?

**Comment by gbooker** [comment] 2020-11-21 13:52
Arg, it was with 5.4.0.  This is what I get for leaving a tab open to remind me to test it; it was on an older release.

5.4.1 did get further but it failed on one of the mods that QModManager loads:
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/5577724/LogOutput.log)

5.3 with the above modifications does not have this issue.

**Comment by denikson** [comment] 2020-11-21 14:11
This looks like a separate issue, I'll move it to #158
