### ISSUE TITLE
Wetland Aspect is missing the air nodegraph

### ISSUE THREAD

**Issue by legokidlogan** [BepInEx/BepInEx#402] opened 2022-04-21 03:00 UTC
### What happened?

The air nodegraph for Wetland Aspect is missing/renamed, causing drones to not move and aerial enemies to not spawn.

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
[Error: Unity Log] Unable to find nodegraph for foggyswamp of type Air.

[Info: Unity Log] Spawn card cscJellyfish (RoR2.CharacterSpawnCard) failed to spawn. Aborting cost procedures.

[Error: Unity Log] Unable to find nodegraph for foggyswamp of type Air.

[Info: Unity Log] Spawn card cscBell (RoR2.CharacterSpawnCard) failed to spawn. Aborting cost procedures.

[Info: Unity Log] <b>[ProperSave]</b> The game saved (Stage: Wetland Aspect)

[Error: Unity Log] ArgumentNullException: 'nodeGraph' must be valid.
Parameter name: nodeGraph
Stack trace:
RoR2.Navigation.NodeGraphSpider..ctor (RoR2.Navigation.NodeGraph nodeGraph, RoR2.HullMask hullMask) (at <7a5120bd69d843a8b8e90b8cce404663>:0)
EntityStates.AI.BaseAIState.PickRandomNearbyReachablePosition () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
EntityStates.AI.Walker.Wander.OnEnter () (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.EntityStateMachine.SetState (EntityStates.EntityState newState) (at <7a5120bd69d843a8b8e90b8cce404663>:0)
RoR2.EntityStateMachine.FixedUpdate () (at <7a5120bd69d843a8b8e90b8cce404663>:0)

[Error: Unity Log] Unable to find nodegraph for foggyswamp of type Air.

[Info: Unity Log] Spawn card cscLesserWisp (RoR2.CharacterSpawnCard) failed to spawn. Aborting cost procedures.
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 5.4.1903 (Most recent version on Thunderstore.io as of writing)
- Game: Risk of Rain 2
```

**Comment by Windows10CE** [comment] 2022-04-21 03:50
This is most likely caused by another mod you have installed, not BepInEx. BepInEx doesn't interact with the game in a meaningful way outside of just loading other plugins.

**Comment by legokidlogan** [comment] 2022-04-21 05:00
Could be `R2API` or `HookGenPatcher` then, unless `StutterStunter` somehow deleted it from memory, though I highly doubt it.

**Comment by ghorsington** [comment] 2022-04-21 05:19
As @Windows10CE said, the issue is likely with some mod; I cannot replicate it on a clean game with stable BepInEx 5.4.19 installed. I suggest going to [Risk of Rain 2 Modding Discord](https://discord.gg/5MbXZvd) and seeking further help related to specific plugins.

Closing the issue for now since it looks more like a plugin-related issue. Please feel free to create a new issue or comment on this one if you manage to replicate this on a clean install without any plugins.

**Closed by ghorsington** 2022-04-21 05:19 UTC
Labels: bug
