### ISSUE TITLE
BepinEx for mac

### ISSUE THREAD

**Issue by 1720222453** [BepInEx/BepInEx#452] opened 2022-07-26 06:11 UTC
### What happened?

I am installing this on a M1 chip mac. I have the latest version of BepInEx and i have followed everything.the steam say:"An error occurred while updating(missing executable)",then this is the error in the terminal "Failed to hook fclose, ignoring it. Error: no such function: fclose
Failed to hook jit_init_version, ignoring it. Error: no such function: mono_jit_init_version"why? I don't know what to do...
Please HELP me! I need your help, please!

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Failed to hook fclose, ignoring it. Error: no such function: fclose
Failed to hook jit_init_version, ignoring it. Error: no such function: mono_jit_init_version
```

### Environment

```markdown
- OS:macOS Monterey version 12.4
- BepInEx: 5.4.21.0
- Game: Dinkum(crossover)
```

**Comment by ghorsington** [comment] 2022-07-26 14:15
Closing as duplicate of #453

**Closed by ghorsington** 2022-07-26 14:15 UTC
Labels: duplicate, needs-replication, error
