### ISSUE TITLE
Help in development

### ISSUE THREAD

**Issue by SakuraMods** [BepInEx/BepInEx#41] opened 2018-07-24 09:18 UTC
Hi, I try to do a extension but it's doesnt work, the message doesn't appear when i press F12.

It's my code and configuration.

![oki](https://user-images.githubusercontent.com/40610556/43128845-41a3b48c-8f33-11e8-83b3-4acc44cca627.png)

**Comment by SakuraMods** [comment] 2018-07-24 09:42
I need extend  "BaseUnityPlugin", now the draw the icon, but can't show in "F12" the message into a developer console.

**Comment by ManlyMarco** [comment] 2018-07-24 19:38
Yes, you have to inherit BaseUnityPlugin for this to work. Check in console if your plugin is loading properly, it should show the test case message then.

**Comment by SakuraMods** [comment] 2018-07-24 20:50
Now i have a new problem.

I have for example this code

`var hFlag = GameObject.FindObjectOfType<HFlag>();`

But can't build the dll because say:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0246	The type or namespace name 'HFlag' could not be found (are you missing a using directive or an assembly reference?)	BexInDescrptor	"MainClass.cs"	61	Active

But i don't now what dll need to add from the game into "references".

**Comment by ManlyMarco** [comment] 2018-07-24 21:03
You need to add Assembly-CSharp.dll from Koikatu_Data\Managed
You might also need other dlls from this directory.

**Comment by SakuraMods** [comment] 2018-07-24 21:18
Thank it's work only with "Assembly-CSharp.dll".

**Comment by denikson** [comment] 2018-07-26 20:41
Seems like the issue is resolved.

I suggest checking out the [plug-in development guide](https://github.com/BepInEx/BepInEx/wiki/How-to-make-a-regular-plugin), as it contains all the information you need to make a plug-in work.

Closing for now; if you have any other issues, feel free to open a new issue,

**Closed by denikson** 2018-07-26 20:41 UTC
